### PR TITLE
fb2def.h incremental update

### PR DESCRIPTION
**Pull request by poire-z**
As discussed in https://github.com/koreader/koreader/issues/3987#issuecomment-392607363 and followups.
See individual commit messages for details.

### CODE REVIEW

**Comment by poire-z** [comment]
Rebased `fb2def.h update 3: add other known HTML block elements` commit to include the CENTER, MENU, DIR and XMP obsoleted elements (but CENTER is so common, even at Wikipedia).
As discussed at https://github.com/koreader/crengine/pull/192#issuecomment-393124598

**Comment by poire-z** [comment]
I may be wrong with making these like `code`.
Should these all be `white-space: pre` or not ? (hard to guess even from MDN).
```
code, kbd, samp, tt {
     white-space: pre;
     font-family: "Droid Sans Mono", "Liberation Mono", "DeJaVu Sans Mono", monospace;
 }
```
https://www.w3.org/TR/CSS22/sample.html shows that only PRE has `white-space: pre`, and CODE has not. But may be it's all as well with `white-space: pre` ?

**Comment by Frenzie** [comment]
No whitespace weirdness please. Newlines, multiple spaces etc. should be ignored. ;)

**Comment by cramoisi** [comment]
@Frenzie : shouldn't `<code>` only use is to keep the whitespace when displaying some code ?

**Comment by Frenzie** [comment]
@cramoisi I'm afraid your example is semantically suboptimal, in possibly all ways actually. :-P

This is how it should be written:

```html
<pre><code>
This preformatted text is code. Maybe SQL.
</code></pre>
```

The `CODE` element itself is no different than `EM`, `STRONG`, etc. 

```html
Here comes an <em>emphasized phrase</em>. Here comes a <code>computerFunction()</code>.

When we wrote <em>bla


bla</em> we expect it to render the same as <em>bla bla</em>. This is no different for <code>bla()

bla()</code>.
```

But I said it was wrong in multiple ways. If `<pre><code></code></pre>` didn't exist, it wouldn't make much sense to stick in a useless `SPAN`! Just write `<pre class="code mono">`. Well, except you shouldn't in that particular example as explained above. ;-)

**Comment by cramoisi** [comment]
hahaha you're right, I even point it out for myself when reviewing the html tags some days ago...
I guess it's only fair that a newbie book has suboptimal code :)

**Comment by Frenzie** [comment]
> I guess it's only fair that a newbie book has suboptimal code

Perhaps, but `<pre class=code><span class=mono>` looks a lot noisier and more difficult to me than a plain `<pre><code>`. I can only assume they were trying to explain classes and ended up doing it in a rather unfortunate way.

**Comment by poire-z** [comment]
That `<pre><code>` trick works as expected, phew.
Above test HTML not wrapped in `<pre>`:
<kbd>image</kbd>
When the whole thing is wrapped in `<pre>`:
<kbd>image</kbd>

Confirming that the text nodes handling is different at HTML parsing time when an element has (from fb2def.h) `white-space: pre`.
So, adding `white-space: pre` to other elements than PRE (and XMP now) in stylesheets, style tweaks, embedded styles, won't work.

**Comment by cramoisi** [comment]
>So, adding white-space: pre to other elements than PRE (and XMP now) in stylesheets, style tweaks, embedded styles, won't work.

?

**Comment by Frenzie** [comment]
I think @poire-z is saying that only default white-space is supported in crengine. :-)

**Comment by cramoisi** [comment]
@poire-z not a problem for me :-)

**Comment by poire-z** [comment]
Ok, found nothing today to add to that PR, so merging in a few.
I'll bumb crengine tomorrow, in case I can fix a few text-formatting mini bugs till then.

**Comment by cramoisi** [comment]
@poire-z I vote for a bump (I want to compile for my reading afternoon reading session :))

**Comment by poire-z** [comment]
> (but I guess i could just patch the diff)

You don't even need that: it's merged, so you just need to:
```
$ cd base/thirdparty/kpvcrlib/
$ git pull
```
and you'll have a crengine _en avance_ that should compile fine.

**Comment by cramoisi** [comment]
great ! Thanks :-)

since we talk about that, if you have the time, could you explain me how I could configure my git local for using the forked repo of the different projet (crengine, koreader and koreader-base). I couldn't figure how to link my local "base" rep to koreader-base for example (and the same thing for crengine), but I don't know if I'm clear

**Comment by poire-z** [comment]
I don't know, probably something with `git remote`, but that's all I ever used :):
```
$ git remote add upstream https://github.com/koreader/koreader.git
$ git remote -v
```

**Comment by cramoisi** [comment]
@poire-z yep I did that ; frenzie must know it  

@Frenzie do you know how I can link my /user/sebatien/koreader/base/ to my github cramoisi/koreader-base ? (and the same for crengine ?)

**Comment by Frenzie** [comment]
I use branches and remotes. The process is described in detail here: http://koreader.rocks/doc/topics/Collaborating.html

Keep in mind you can also specify a custom `KOR_BASE` environment variable to point to a different directory.

If I want to test your crengine, what I do is something like this (in the crengine folder):

```bash
# you can name the remote whatever you like
git remote add cramoisi git://github.com/cramoisi/crengine.git
# you can obviously also name the new branch whatever you like
git checkout -b wowthesehyphenationpatternslookprettycomplex
# but the `update-fr-de-pattern` branch was named by the other dev
git pull cramoisi update-fr-de-pattern
```

For my own stuff that's similar, except then I can also push to my own remote if I like.

```
git push frenzie code-quality-ci-stuff
```

But if I'm just doing something small and simple (as is usually the case in crengine) I tend to work with `git stash` and `git stash pop`, combined with just copying a couple of files to my other crengine repo. It's faster than the fancy branch stuff. Or even just local branches and copying a couple of files around. It really depends.

For the most part I only need the slightly fancier Git features on the front and base repos.

You can also use tools like Git Cola or QGit to assist with managing your Git repo. The reason I mention those two is personal bias; there are many more.

**Comment by cramoisi** [comment]
@Frenzie ok, I already use branches and remote. I was wondering it is was simpler or not to make one tree with everything, locally speaking (and not to have /sebastien/koreader ; /sebastien/crengine ; /sebastien/koreader-base but having /sebastien/koreader ; /sebastien/koreader/base and /sebastien/koreader/base/thirdparty/crengine).

**Comment by poire-z** [comment]
A small thing about CENTER (which is just a block element with `text-align: center`)
If you have this:
```html
<div>
Some text in a DIV
<center>
Some text in CENTER, and now a TABLE:
<table style="border: black 1px solid">
<tr><td>cell 11</td><td>cell 12 longer</td></tr>
<tr><td>cell 21</td><td>cell 22</td></tr>
</table>
</center>
</div>

<div>
Some text in a DIV
<center>
Some text in CENTER, and now some UL LI:
<ul>
<li>list item 1</li>
<li>list item 2 longer</li>
</ul>
</center>
</div>
```
KOReader would render it as this:
<kbd>image</kbd>

(crengine can't really shorten the width of the TABLE or LI the way it works)
I guess that's because `text-align: center` is inherited by all children elements. I haven't found any specs saying that `text-align` inheritance should stop on some elements like TABLE or UL.

But on Firefox, it is rendered as:
<kbd>image</kbd>

If I add:
```html
<style>
table {text-align: left;}
ul {text-align: left;}
</style>
```
to stop the text-align inheritance, KOReader displays it as:
<kbd>image</kbd>

Should we add in `epub.css`  `{text-align: left;}` for some block elements so their default value is `left` and not `inherit` ? and which?

I often meet that kind of stuff in Wikipedia epubs:
<kbd>image</kbd>

**Comment by Frenzie** [comment]
@cramoisi I'd say that as soon as copying one or two files around starts to feel like a drag it's probably time to switch to "proper" remotes and branches but for the types of PRs you and I do on crengine I personally seldom use them within the main KOReader tree.

@poire-z I suspect it's an oddity of tables, not of text-align.

**Pull request merged**
