### PR TITLE
cherry pick markdown support from crengine-ng

### PR DESCRIPTION
**Pull request by benoit-pierre**
Only the md4c code path.

This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/606)

### CODE REVIEW

**Review by poire-z — APPROVED** [review]
Looks ok.

**Comment by NiLuJe** [comment]
I'd possibly split this into at least two commits to split authorship as relevant (we, err, know that the author in question is a bit touchy on that subject ^^).

**Comment by benoit-pierre** [comment]
> I'd possibly split this into at least two commits to split authorship as relevant (we, err, know that the author in question is a bit touchy on that subject ^^).

And he's right, amended with proper attribution. I don't think this need to be split in multiple commits, however.

**Review by poire-z — APPROVED** [review]

**Comment by NiLuJe** [comment]
> I don't think this need to be split in multiple commits, however.

Yup, I was confusing the two PRs together and thinking of buildsystem stuff ;).

**Pull request merged**
