### PR TITLE
Selectable kerning methods: disabled / freetype / harfbuzz 

### LINKED ISSUE #224: Harfbuzz
Do. Want.

(not spamming the other repo)
```
github.com/buggins/coolreader/pull/24
```

It looks amazingly uninvolved at a quick glance. (The PR is gigantic, but most of that is just harfbuzz itself.)

### PR DESCRIPTION
**Pull request by poire-z**
See #224.
Includes from upstream:
- Harfbuzz kerning: https://github.com/buggins/coolreader/pull/24 https://github.com/buggins/coolreader/pull/29
- Fix integer overflow in glyph origin https://github.com/buggins/coolreader/commit/195b53ee

Kerning methods made selectable: `Off / Freetype / Harfbuzz` as Harfbuzz shaping it a bit slower than pure-freetype, but it is perfectly usable on small books, and on big books once a cache has been built. It's just the rendering when toggling an other option that will take a bit longer to re-render the document.

Anyway, it looks like harfbuzz does more than kerning by default, and does some Right-To-Left shaping of words in arabic (I can't read, but it _looks_ like they are reversed :) , but only on the word level: in the sentence/line, they are in a Left-To-Right order (as they are in the HTML). I guess that would be lvtextfm.cpp work to do it on the line level.

Another thing I forgot to add as a comment, but did not investigate much: the lines like:
`hb_feature_from_string("+kern", -1, &_hb_kern_feature);`
do not seem to change harfbuzz behaviour. Even when not requesting `+kern`, we get ligatures (so, may be these are different _features_, and ligatures are enabled by default).
For reference: https://www.preusstype.com/techdata/features.php (I tried to enable a few, got no change in my sample text).

Closes #224.

### CODE REVIEW

**Comment by poire-z** [comment]
Just adding some notes I found for reference:

https://lists.freedesktop.org/archives/harfbuzz/2015-December/005381.html
```
The OpenType model positions glyphs from left to right always, HarfBuzz
should give you the glyphs and positions in their visual order, so after
shaping you don’t need to care whether the text was LTR or RTL (until
you start doing line breaking, because it need to be done in logical
order).
```

https://lists.freedesktop.org/archives/harfbuzz/2015-December/005387.html
about `hb_buffer_guess_segment_properties`, that we use, that guesses some words are RTL:
```
HarfBuzz does not do an such detection by default (there is the guess
segment properties function, but it does very simplistic detection and
is meant only for quick testing, not real world use).
```

https://lists.freedesktop.org/archives/harfbuzz/2015-August/005036.html
links to various harfbuzz incomplete documentations

**Comment by Frenzie** [comment]
Well, I guess I can just read a book whenever I was planning to look into this. Thanks! :-D

**Comment by poire-z** [comment]
It's been disabled today in the other repo.
But as it's a toggable for us, and the default is still freetype-only, and I tried to make sure no harfbuzz code was used (except some data structure initialisation, that have no noticable impact on performances), it should be fine to merge, so people can taste a bit of HarfBuzz.
Just curious if you'll find that with it, _E Ink can look finally as good as cheap newspaper_ :)

**Comment by Frenzie** [comment]
MuPDF (in EPUB as well as PDF) already does that. Including literally. The [NRC](https://en.wikipedia.org/wiki/NRC_Handelsblad) subscription includes downloadable PDFs of the articles. (Not that I stick them on the ereader… but I could.)

**Comment by virxkane** [comment]
This line
[code]
hb_feature_from_string("+kern", -1, &_hb_kern_feature);
[/code]
enable kerning feature. If you don't look difference maybe you font don't have any kerning table.

**Comment by virxkane** [comment]
Maybe there? See HB_TAG
https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-shape.cc

**Comment by poire-z** [comment]
Just mentionning that (no intent to investigate):
Standalone paragraph with arabic or hebrew text is badly rendered with harfbuzz, like one glyph per line, which make the number of pages rise like rabbits :) (it's still ok for inline arabic or hebrew in english text).
With freetype, it is rendered on a line, ok, still LTR badly, but it doesn't have any impact on the rest of the book.
So, another reason to stick with freetype as the default.
(can be tested with the EPUB available at https://www.mobileread.com/forums/showthread.php?t=211123)

**Comment by poire-z** [comment]
Mentionning this Mobiread post, with some sample EPUB mixing english and persian words, and screenshots of how it should look: https://www.mobileread.com/forums/showthread.php?p=3828770#post3828770
(It renders badly for us with "best", just as explained in my previous post above.)

**Pull request merged**
