### PR TITLE
Update reference to default english hyph dict

### PR DESCRIPTION
**Pull request by poire-z**
Follow up to #206
(also needs to be updated in cre.cpp)

### CODE REVIEW

**Comment by cramoisi** [comment]
the line in cr3.ini regarding the hyph dic comes from here ? (even if i don't understand it's real use : i deleted the pdb file months ago and haven't seen anything wrong or bad)

**Comment by cramoisi** [comment]
(@poire-z  : I mean I know what it does at the opening of a document, but what's the point, exactly ? It looks like a problem to me to have a file subject to variation hardcoded inside cr3)

**Comment by poire-z** [comment]
I updated them because I got unit test failures, and I wanted to rule a possible change because no hyphenation were used (and because people may still have the .pdb sitting on their device - dunno how much OTA can get rid of removed files - and so crengine starts with the new ones, even if we set another one later on first book opening).
The cr3.ini is created on first run (when it doesn't exist), with hardcoded defaults from crengine and our base/cre.cpp. It's of no real use for us (as we set all defaults fom koreader lua at each book opening). It's just a left-over from CoolReader, where the library crengine does a bit of the initialization/defaults management that would have been better left to the application side.
(Would be quite a bit of work to clean crengine of all that)

**Comment by cramoisi** [comment]
@poire-z 
about cr3.ini : Some days ago, I tests some of the options of cr3.ini (related to the header) and some of them still works : the chapter markers, the display of the page, the progression percentage, the display of the battery status.

about pdb hyph files : are you ok if I check pdb against pattern and convert the rest of the pdb files to pattern files ? They will contains at least the exact sames rules but the files will be human-readable ready for anybody who want to improve them.

**Comment by poire-z** [comment]
> are you ok if I check pdb against pattern and convert the rest of the pdb files to pattern files 

No problem for me with updating them.

What happens to people who have in their settings.reader.lua:
`["hyph_alg_default"] = "Bulgarian_hyphen_(Alan).pdb",`
and in their metadata.lua:
`["hyph_alg"] = "Bulgarian_hyphen_(Alan).pdb",`
once the .pdb has disappeared?

**Comment by cramoisi** [comment]
They will fallback to the fallback (I tested).
the problem is : if the fallback are the one which is removed, it's go to none.

**Comment by cramoisi** [comment]
(another thing : i just did that with english :-) and did that with french before ; and we did that with german, dutch, spanish before. It's more like people with see there is something going wrong (because no hyph at all in the case of the fallback removed) and they will recheck in the menu. It's not really a problem.

But one good solution would be to open the readme at first after each update and saying to people if there is some things to look at (or change the code).

**Comment by cramoisi** [comment]
If you're ok, i'm ok then. Shall I wait 1 one to see if people are angry ? :-p

**Comment by poire-z** [comment]
You don't need to wait to push a PR, it's the merge that matters.
A few days before merging maybe? (although if we have any english or american user, we don't see them complaining often here :) so they won't say much if they are angry :)

**Pull request merged**
