### PR TITLE
Factorize ldomXPointer::getRect() and getRectEx()

### PR DESCRIPTION
**Pull request by poire-z**
They share much of the same code, that we can add a default parameter to `getRect(rect, extended=false)` to get one behaviour or the other.

I noted in #158:
> getRectEx() was introduced in #51 and #52 (it could have been made simpler by just passing an optional parameter to the existing getRect()).

and while trying to fix other things, when not really knowing which of the 2 will be called, I often have to put the same printf or tries for fix in both, which complicate things.

Pinging @frankyifei for comments and ack, as he added it in #52.

A full diff of getRect and getRectEx shows as:
```c
--- getrectClassic.cpp  2018-05-15 15:40:17.687306044 +0200
+++ getrectEx.cpp       2018-04-22 13:32:41.144950452 +0200
@@ -1,202 +1,206 @@
-/// returns caret rectangle for pointer inside formatted document
-bool ldomXPointer::getRect(lvRect & rect) const
+/// returns caret rectangle for pointer inside formatted document considering paddings and borders
+bool ldomXPointer::getRectEx(lvRect & rect) const
 {
     //CRLog::trace("ldomXPointer::getRect()");
     if ( isNull() )
         return false;
     ldomNode * p = isElement() ? getNode() : getNode()->getParentNode();
     ldomNode * p0 = p;
     ldomNode * finalNode = NULL;
     if ( !p ) {
         //CRLog::trace("ldomXPointer::getRect() - p==NULL");
     }
     //printf("getRect( p=%08X type=%d )\n", (unsigned)p, (int)p->getNodeType() );
     if ( !p->getDocument() ) {
         //CRLog::trace("ldomXPointer::getRect() - p->getDocument()==NULL");
     }
     ldomNode * mainNode = p->getDocument()->getRootNode();
     for ( ; p; p = p->getParentNode() ) {
         int rm = p->getRendMethod();
         if ( rm == erm_final || rm == erm_list_item || rm == erm_table_caption ) {
             finalNode = p; // found final block
         } else if ( p->getRendMethod() == erm_invisible ) {
             return false; // invisible !!!
         }
         if ( p==mainNode )
             break;
     }

     if ( finalNode==NULL ) {
         lvRect rc;
         p0->getAbsRect( rc );
         CRLog::debug("node w/o final parent: %d..%d", rc.top, rc.bottom);
     }

     if ( finalNode!=NULL ) {
         lvRect rc;
         finalNode->getAbsRect( rc );
         if (rc.height() == 0 && rc.width() > 0) {
             rect = rc;
             rect.bottom++;
             return true;
         }
         RenderRectAccessor r( finalNode );
         //if ( !r )
         //    return false;
         LFormattedTextRef txtform;
         finalNode->renderFinalBlock(
-             txtform,
-             &r,
-             r.getWidth()
+                txtform,
+                &r,
+                r.getWidth()
                 -measureBorder(finalNode,1)
                 -measureBorder(finalNode,3)
                 -lengthToPx(finalNode->getStyle()->padding[0],
                             rc.width(),
                             finalNode->getFont()->getSize())
                 -lengthToPx(finalNode->getStyle()->padding[1],
                             rc.width(),
                             finalNode->getFont()->getSize()));

         ldomNode *node = getNode();
+        rc.top+=measureBorder(finalNode,0)+lengthToPx(finalNode->getStyle()->padding[2],r.getWidth(),finalNode->getFont()->getSize());
+        rc.left+=measureBorder(finalNode,3)+lengthToPx(finalNode->getStyle()->padding[0],r.getWidth(),finalNode->getFont()->getSize());
+        rc.right+=measureBorder(finalNode,3)+lengthToPx(finalNode->getStyle()->padding[0],r.getWidth(),finalNode->getFont()->getSize());
+        rc.bottom+=measureBorder(finalNode,0)+lengthToPx(finalNode->getStyle()->padding[2],r.getWidth(),finalNode->getFont()->getSize());
         int offset = getOffset();
 ////        ldomXPointerEx xp(node, offset);
 ////        if ( !node->isText() ) {
 ////            //ldomXPointerEx xp(node, offset);
 ////            xp.nextVisibleText();
 ////            node = xp.getNode();
 ////            offset = xp.getOffset();
 ////        }
 //        if ( node->isElement() ) {
 //            if ( offset>=0 ) {
 //                //
 //                if ( offset>= (int)node->getChildCount() ) {
 //                    node = node->getLastTextChild();
 //                    if ( node )
 //                        offset = node->getText().length();
 //                    else
 //                        return false;
 //                } else {
 //                    for ( int ci=offset; ci<(int)node->getChildCount(); ci++ ) {
 //                        ldomNode * child = node->getChildNode( offset );
 //                        ldomNode * txt = txt = child->getFirstTextChild( true );
 //                        if ( txt ) {
 //                            node = txt;
 ////                            lString16 s = txt->getText();
 ////                            CRLog::debug("text: [%d] '%s'", s.length(), LCSTR(s));
 //                            break;
 //                        }
 //                    }
 //                    if ( !node->isText() )
 //                        return false;
 //                    offset = 0;
 //                }
 //            }
 //        }

         // text node
         int srcIndex = -1;
         int srcLen = -1;
         int lastIndex = -1;
         int lastLen = -1;
         int lastOffset = -1;
         ldomXPointerEx xp(node, offset);
         for ( int i=0; i<txtform->GetSrcCount(); i++ ) {
             const src_text_fragment_t * src = txtform->GetSrcInfo(i);
             bool isObject = (src->flags&LTEXT_SRC_IS_OBJECT)!=0;
             if ( src->object == node ) {
                 srcIndex = i;
                 srcLen = isObject ? 0 : src->t.len;
                 break;
             }
             lastIndex = i;
             lastLen =  isObject ? 0 : src->t.len;
             lastOffset = isObject ? 0 : src->t.offset;
             ldomXPointerEx xp2((ldomNode*)src->object, lastOffset);
             if ( xp2.compare(xp)>0 ) {
                 srcIndex = i;
                 srcLen = lastLen;
                 offset = lastOffset;
                 break;
             }
         }
         if ( srcIndex == -1 ) {
             if ( lastIndex<0 )
                 return false;
             srcIndex = lastIndex;
             srcLen = lastLen;
             offset = lastOffset;
         }
         for ( int l = 0; l<txtform->GetLineCount(); l++ ) {
             const formatted_line_t * frmline = txtform->GetLineInfo(l);
             for ( int w=0; w<(int)frmline->word_count; w++ ) {
                 const formatted_word_t * word = &frmline->words[w];
                 bool lastWord = (l == txtform->GetLineCount() - 1
                                  && w == frmline->word_count - 1);
                 if ( word->src_text_index>=srcIndex || lastWord ) {
                     // found word from same src line
                     if ( word->flags == LTEXT_WORD_IS_OBJECT
-                            || word->src_text_index > srcIndex
-                            || offset <= word->t.start ) {
+                         || word->src_text_index > srcIndex
+                         || offset <= word->t.start ) {
                         // before this word
                         rect.left = word->x + rc.left + frmline->x;
                         //rect.top = word->y + rc.top + frmline->y + frmline->baseline;
                         rect.top = rc.top + frmline->y;
-                        rect.right = rect.left + 1;
+                        rect.right = rect.left + word->width;
                         rect.bottom = rect.top + frmline->height;
                         return true;
                     } else if ( (offset < word->t.start+word->t.len)
-                               || (offset==srcLen
-                                   && offset == word->t.start+word->t.len) ) {
+                                || (offset==srcLen
+                                    && offset == word->t.start+word->t.len) ) {
                         // pointer inside this word
                         LVFont *font = (LVFont *) txtform->GetSrcInfo(srcIndex)->t.font;
                         lUInt16 w[512];
                         lUInt8 flg[512];
                         lString16 str = node->getText();
                         font->measureText(
-                            str.c_str()+word->t.start,
-                            offset - word->t.start,
-                            w,
-                            flg,
-                            word->width+50,
-                            '?',
-                            txtform->GetSrcInfo(srcIndex)->letter_spacing);
+                                str.c_str()+word->t.start,
+                                offset - word->t.start,
+                                w,
+                                flg,
+                                word->width+50,
+                                '?',
+                                txtform->GetSrcInfo(srcIndex)->letter_spacing);
                         int chx = w[ offset - word->t.start - 1 ];
                         rect.left = word->x + chx + rc.left + frmline->x;
                         //rect.top = word->y + rc.top + frmline->y + frmline->baseline;
                         rect.top = rc.top + frmline->y;
-                        rect.right = rect.left + 1;
+                        rect.right = rect.left + word->width;
                         rect.bottom = rect.top + frmline->height;
                         return true;
                     } else if (lastWord) {
                         // after last word
                         rect.left = word->x + rc.left + frmline->x + word->width;
                         //rect.top = word->y + rc.top + frmline->y + frmline->baseline;
                         rect.top = rc.top + frmline->y;
-                        rect.right = rect.left + 1;
+                        rect.right = rect.left + word->width;
                         rect.bottom = rect.top + frmline->height;
                         return true;
                     }
                 }
             }
         }
         return false;
     } else {
         // no base final node, using blocks
         //lvRect rc;
         ldomNode * node = getNode();
         int offset = getOffset();
         if ( offset<0 || node->getChildCount()==0 ) {
             node->getAbsRect( rect );
             return true;
             //return rc.topLeft();
         }
         if ( offset < (int)node->getChildCount() ) {
             node->getChildNode(offset)->getAbsRect( rect );
             return true;
             //return rc.topLeft();
         }
         node->getChildNode(node->getChildCount()-1)->getAbsRect( rect );
         return true;
         //return rc.bottomRight();
     }
 }
```

And with diff -b (ignoring white space changes):
```c
--- getrectClassic.cpp  2018-05-15 15:40:17.687306044 +0200
+++ getrectEx.cpp       2018-04-22 13:32:41.144950452 +0200
@@ -1,5 +1,5 @@
-/// returns caret rectangle for pointer inside formatted document
-bool ldomXPointer::getRect(lvRect & rect) const
+/// returns caret rectangle for pointer inside formatted document considering paddings and borders
+bool ldomXPointer::getRectEx(lvRect & rect) const
 {
     //CRLog::trace("ldomXPointer::getRect()");
     if ( isNull() )
@@ -58,6 +58,10 @@
                             finalNode->getFont()->getSize()));

         ldomNode *node = getNode();
+        rc.top+=measureBorder(finalNode,0)+lengthToPx(finalNode->getStyle()->padding[2],r.getWidth(),finalNode->getFont()->getSize());
+        rc.left+=measureBorder(finalNode,3)+lengthToPx(finalNode->getStyle()->padding[0],r.getWidth(),finalNode->getFont()->getSize());
+        rc.right+=measureBorder(finalNode,3)+lengthToPx(finalNode->getStyle()->padding[0],r.getWidth(),finalNode->getFont()->getSize());
+        rc.bottom+=measureBorder(finalNode,0)+lengthToPx(finalNode->getStyle()->padding[2],r.getWidth(),finalNode->getFont()->getSize());
         int offset = getOffset();
 ////        ldomXPointerEx xp(node, offset);
 ////        if ( !node->isText() ) {
@@ -141,7 +145,7 @@
                         rect.left = word->x + rc.left + frmline->x;
                         //rect.top = word->y + rc.top + frmline->y + frmline->baseline;
                         rect.top = rc.top + frmline->y;
-                        rect.right = rect.left + 1;
+                        rect.right = rect.left + word->width;
                         rect.bottom = rect.top + frmline->height;
                         return true;
                     } else if ( (offset < word->t.start+word->t.len)
@@ -164,7 +168,7 @@
                         rect.left = word->x + chx + rc.left + frmline->x;
                         //rect.top = word->y + rc.top + frmline->y + frmline->baseline;
                         rect.top = rc.top + frmline->y;
-                        rect.right = rect.left + 1;
+                        rect.right = rect.left + word->width;
                         rect.bottom = rect.top + frmline->height;
                         return true;
                     } else if (lastWord) {
@@ -172,7 +176,7 @@
                         rect.left = word->x + rc.left + frmline->x + word->width;
                         //rect.top = word->y + rc.top + frmline->y + frmline->baseline;
                         rect.top = rc.top + frmline->y;
-                        rect.right = rect.left + 1;
+                        rect.right = rect.left + word->width;
                         rect.bottom = rect.top + frmline->height;
                         return true;
                     }
```

### CODE REVIEW

**Comment by Frenzie** [comment]
I'm not familiar with the code paths involved but the diff shows nothing that "smells".

**Comment by frankyifei** [comment]
I remember there was a bug in cre.cpp that has to be fixed from crengine side. Ex is only called in cre.cpp so I can change things without change internal of crengine. I did not want to touch getrect because it was used extensively in crengine at that time.

**Comment by poire-z** [comment]
@frankyifei : I understand what you did in #51 / #52, and we'll still have `getRect(r)` and `getRectEx(r)` called and do exactly what they currently do.

It's just that your getRectEx looks too very similar to getRect, that it's bothering at some occasions that they have the nearly same code duplicated.

So, this PR adds an optional parameter to `getRect(r, extended=false)`, and the changes you made for getRectEx are integrated to getRect, but executed only when `extended=true`.
So, all calls (from crengine or cre.cpp) to `getRect(r)` is similar to calling `getRect(r, extended=false)` and have the current getRect() code executed.
And getRectEx is now defined as `getRectEx(lvRect & rect) { return getRect(rect, true); };` so all calls to `getRextEx()` execute the same code (getRect) with `extended=true`, that means getRect with your getRectEx changes.

So, yes, we touch the original getRect, but we have touched so many other things recently... :)

**Comment by poire-z** [comment]
Thanks for the thumbs up, I take that as OK for merging :)
(No need to bump this yet.)

**Pull request merged**
