### PR TITLE
Round FT metrics, split text drawing by unicode script, and others

### PR DESCRIPTION
**Pull request by poire-z**
See individual commit messages for detail.

Links to relevant discussions:
- Fix decoding of recent MOBI files https://github.com/koreader/koreader/issues/5599
- Fonts: round FT metrics instead of floor'ing them https://github.com/koreader/koreader-base/pull/1010#issuecomment-554565855
- Fonts: switch to no hinting when native hinting fails https://github.com/koreader/koreader/pull/5553#issuecomment-548509004 (with the font from https://www.mobileread.com/forums/showthread.php?t=273339)
- Text: split measuring and word drawing by unicode script https://github.com/koreader/koreader/issues/5359#issuecomment-533211988

Before (with that Isidore font and native hinting, so "abc" not shown):
<kbd>image</kbd>
(at the bottom, no space on one side or both of the arabic "word" - might just be a stream of reandom arabic chars.)
After:
<kbd>image</kbd>

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/318)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Yay, inline quotes still quoting unrelated code! :D.

The reviewable link actually points to the right place.

**Comment by Frenzie** [comment]
Yeah, like I said in base I was almost already sold when I saw the whitespace. ;-)

**Comment by poire-z** [comment]
> My maths is fuzzy, but isn't this missing the AND from ROUND?

I figured (and checked with some online C compiler with values 63, 65, 90, 100, 127, 130... and -63 -65... that both ways always give the same result) that `& -64` (which do `& 0xfffffffff000000`, setting to 0 the 6 lower bits) is not needed if you do just after `>> 6`.

> Also, metrics, not metric ;).

Even when I'm dealing with a single one (height, or advance, or another) of the multiple font metrics?
Should it be `FONT_METRICS_TO_PX(single_metrics)` ?! 

> I CAN SEE DEAD WHITESPACE

That's some comment about that "reviewable" site, or my use of added white space to keep things aligned?

Anyway, not fond of "reviewable" (except for the larger width & smaller font size when viewing code) - and the noise it adds here, and it forcing me to resolve conversation there, and masquerading as an additional CI check. But if you guys like it... (Except that now, as I don't want to use it, I can reply to code comments in the main PR thread and not miss some of them :)

**Comment by NiLuJe** [comment]
> > My maths is fuzzy, but isn't this missing the AND from ROUND?
> 
> I figured (and checked with some online C compiler with values 63, 65, 90, 100, 127, 130... and -63 -65... that both ways always give the same result) that `& -64` (which do `& 0xfffffffff000000`, setting to 0 the 6 lower bits) is not needed if you do just after `>> 6`.
> 

Yeah, ran a quick `for (int32_t i = INT32_MIN; i < INT32_MAX; i++) {` check locally, too ;).

> > Also, metrics, not metric ;).
> 
> Even when I'm dealing with a single one (height, or advance, or another) of the multiple font metrics?
> Should it be `FONT_METRICS_TO_PX(single_metrics)` ?!
> 

Yup. c.f., OED ;).

Screenshot_20191122_011849


> > I CAN SEE DEAD WHITESPACE
> 
> That's some comment about that "reviewable" site, or my use of added white space to keep things aligned?
> 
> Anyway, not fond of "reviewable" (except for the larger width & smaller font size when viewing code) - and the noise it adds here, and it forcing me to resolve conversation there, and masquerading as an additional CI check. But if you guys like it... (Except that now, as I don't want to use it, I can reply to code comments in the main PR thread and not miss some of them :)

Yeah, that was in response to @Frenzie in another issue and/or on gitter ;).

**Comment by NiLuJe** [comment]
Just to clear up the maths in my head:

Two's complement arithmetic say that (for an int) `-x == (~x) + 1 == ~(x - 1)`, and that `~x == (x ^ 0xFFFFFFFF)`.
Meaning `-64 == (63 ^ 0xFFFFFFFF)`. That's `4294967232`, or `0b11111111111111111111111111000000`.

Hence the 6 low bits, which we then punt off with the shift ;).

**Comment by poire-z** [comment]
> I don't think I've ever seen it being used in another form in the context of font design/rendering.

I'm not convinced :) Your screenshots explicitely states its use in plural, and show examples in plurals.
Looking at the number of results of a google search (for what it's worth) for "one metric" vs "one metrics", or "single metric" vs "single metrics", gives more result for the singular "metric" - and there's some links to scientific papers (which I guess go thru grammar reviews :) that use the singular.
And there's a few singular "metric" instances in FreeType sources (albeit far less than plural "metrics" - but there are more generic comments not specifying a specific single metric :)

**Comment by poire-z** [comment]
(Small optimization to the "background-color black" commit.)

**Comment by NiLuJe** [comment]
Oh, that's because the singular form is *for sure* more common *in general* ;). A slightly different meaning, and different contexts, though ;).

Screenshot_20191122_194059

In FreeType, the only singular I can find are related to the PCF driver, which may be using it because of said slightly different meaning ;).

**Comment by poire-z** [comment]
Well, I'm older too :) But ok, history will blame that on me (and it looks so odd to my french-grammar-rooted english :)

**Comment by Frenzie** [comment]
Afaik a metric is basically just a synonym for measurement (e.g., what metric should we use to judge X). One metric, two metrics. Height, ascent, descent, and whatever else there is are all individually a single font metric.

As in this quote (2011 April 10, Financial Times, according to [here](https://en.wiktionary.org/wiki/metric)):

> As for the large number of official statements that Spain is safe, I think they are merely a metric of the complacency that has characterised the European crisis from the start.

Also:

https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-obtain-font-metrics

> Note that this is the same as the number (rounded up to an integer) obtained by converting the line-spacing metric to pixels.

**Comment by NiLuJe** [comment]
Yeah, I'm a bit torn on the specific usage where it's used to specifically point to a single specific type like in that last quote ;).

That said, here, I'm taking the macro to basically say "convert *some* metrics to pixels", so the plural seems justified nonetheless.

Grammar is fun. Feel free to poke holes in that ;).

**Pull request merged**
