### PR TITLE
Fix possible segfault with LVIndexedRefCache.cache()

### PR DESCRIPTION
**Pull request by poire-z**
When loading a document, in very rare circumstances, ldomNode::initNodeStyle() would end up with a NULL
style (it shouldn't), that would later cause a segfault in ldomNode::initNodeFont() where that style is accessed.

A segfault happens (and happens too with a 3 months old crengine) with this epub [Leonard de Vinci.FR.epub.zip](https://github.com/koreader/crengine/files/1889729/Leonard.de.Vinci.FR.epub.zip).
It's a Wikipedia article saved as EPUB with no image.

If you just change in koreader `data/epub.css`:
`b, strong { font-weight: bold; }`
to
`b, strong { font-weight: normal; }` or `b, strong { font-weight: bolder; }`
it does not happen!
If you remove or rename to `<zzz>` 1 of the 3 `<b>stuff</b>` in the content.html, it does not happen!
If you save it again as EPUB, with images (all, or aborted just after 1 or 2 images): it does not happen!

Althought I tracked it down to where the problem is (see my long comment in the diff), I have no idea why it happened so very rarely, that there was an existing `indexholder` that was not referenced in the cache (and it has not been `release()`'d previously, only `tinyNodeCollection::clearNodeStyle()` seems to be able to do that, and it was not called). So, it's probably a bug somewhere else, but I couldn't track it.
(I first thought it was a style hash collision - but I think it is not - although it may very well be something like that for it to happen so rarely, and not happen when you tweak a few things, like removing/changing 1 single `<b>` tag in the content.html...)

On the loading of this epub, the problem is noticed here:
https://github.com/koreader/crengine/blob/925bae617252aa036ea875700dbec46661796f47/crengine/src/lvrend.cpp#L2801-L2805

The stuff fixed by this PR is used there:
https://github.com/koreader/crengine/blob/925bae617252aa036ea875700dbec46661796f47/crengine/src/lvtinydom.cpp#L1681-L1685

The segfault would happen around there (where s.get() would return NULL):
https://github.com/koreader/crengine/blob/925bae617252aa036ea875700dbec46661796f47/crengine/src/lvtinydom.cpp#L10945-L10954

Some bits of logs with some printf here and there:
Before:
```
initNodeStyle 17fd3
before 0 df2d2830
newindex: 134  /  provided indexholder: 0
_styles.cache: 1, 134, df2d2830
fntIndex 0
good
initNodeStyle 17fe3
before 0 df2d2830
newindex: 11  /  provided indexholder: 0
_styles.cache: 1, 11, df2d2830
fntIndex 1
initNodeStyle 17ff3
before 0 df2d2860
newindex: 10  /  provided indexholder: 0
_styles.cache: 1, 10, df2d2860
fntIndex 1
initNodeStyle 18003
before 135 df2d2830
newindex: 135  /  provided indexholder: 135
released: refcount for 135 = 1
_styles.cache: 0, 135, df2d2830
Null style returned for index 135
NULL style set!!!
before 135 df2d2830  (this is the retried enode->setStyle( style );  in lvrend.cpp)
newindex: 135  /  provided indexholder: 135
released: refcount for 135 = 1
_styles.cache: 0, 135, df2d2830
fntIndex 0
oups 18003
Null style returned for index 135
NULL style is set for <b>
Null style returned for index 135
Null style returned for index 135
Segmentation fault
*** Segmentation fault
```

After:
```
initNodeStyle 17fd3
before 0 d181f900
new: refcount for 134 = 1
newindex: 134  /  provided indexholder: 0
_styles.cache: 1, 134, d181f900
fntIndex 0
good
refcount for 1 = 2894
initNodeStyle 17fe3
before 0 d181f900
refcount for 11 = 27
newindex: 11  /  provided indexholder: 0
_styles.cache: 1, 11, d181f900
fntIndex 1
initNodeStyle 17ff3
before 0 d181f930
refcount for 10 = 29
newindex: 10  /  provided indexholder: 0
_styles.cache: 1, 10, d181f930
fntIndex 1
initNodeStyle 18003
before 135 d181f900
new: refcount for 135 = 1
newindex: 135  /  provided indexholder: 135
_styles.cache: 0, 135, d181f900
fntIndex 0
good
refcount for 11 = 2
before 4 d181f718
new: refcount for 136 = 1
newindex: 136  /  provided indexholder: 4
_styles.cache: 1, 136, d181f718
...
```

### CODE REVIEW

**Comment by Frenzie** [comment]
You should look into using either gdb itself (harder) or some friendly frontend. ;-) (As I automated through ./kodev run --gdb.)

Nothing immediately pops out and I don't want to get into setting breakpoints atm but it's very useful to quickly get a better handle on what the program is doing.

screenshot_2018-04-09_14-40-00

screenshot_2018-04-09_14-37-33

**Comment by Frenzie** [comment]
This is what a healthy getFont looks like:

screenshot_2018-04-09_14-43-38

And you get this weirdness when the segmentation fault occurs.

screenshot_2018-04-09_14-44-25

**Comment by poire-z** [comment]
Yeah, I guess so.
But i have some very old bad memories of playing with gdb, and have the feeling I would need to hit continue 1233 times on a breakpoint if it sefgaults while processing the 1234th node style...
Somehow, I'm more at ease with logs and browsing them with vi, and just adding printf around what I suspect :)

Also, I don't plan on making a career of debugging crengine :)
(Given the beast it is, and the amount of work put into it 8 years ago by a single person, I find it amazingly well done and stable. It just lacks more comments to allow people to get into it quicker.)

**Comment by Frenzie** [comment]
> have the feeling I would need to hit continue 1233 times on a breakpoint if it sefgaults while processing the 1234th node style...

True, but that's part of why you minimize the testcase. ;-)

(Of course in this case it looks like the entire issue disappears with even minute changes but I didn't look too hard.)

> It just lacks more comments to allow people to get into it quicker.

That, and even though it might say ".cpp" it's really more C with a sprinkling of C++ than real C++. Which at least to me is for the worse.

**Comment by Frenzie** [comment]
Well sure, public and private and all that stuff is C++, but I'd argue a lot of that is more about how you use the language than what the compiler does. You can enact various practices like private headers in plain old C quite simply by never including private headers. A C++ compiler will crash, but in C you'll be dependent on naming it `lvrefcachePRIVATEPRIVATEPRIVATEDONOTINCLUDE-IREPEATDONOTINCLUDE(exceptinlvrefcache).h` and abiding by it. A bit like how in front we sometimes use `Module:_functionName()` but don't always strictly abide by the private part. (Oops. :-P) I understand you can also implement classes with self-referencing pointers and stuff, the main problem being it'd be a lot harder to change later.

crengine just strikes me as somewhat C-ish. But it'd probably be more accurate to call it oldish C++, which I imagine was mostly C with objects back when it was new anyway. And perhaps not even that old, just not C++11 or newer (obviously ;-)).

Microsoft gives [this example](https://msdn.microsoft.com/en-us/library/hh279654.aspx) (right under the fairly relevant "Modern C++ emphasizes" list):

## Old

```c
// circle and shape are user-defined types  
circle* p = new circle( 42 );   
vector<shape*> v = load_shapes();  
  
for( vector<circle*>::iterator i = v.begin(); i != v.end(); ++i ) {  
    if( *i && **i == *p )  
        cout << **i << “ is a match\n”;  
}  
  
for( vector<circle*>::iterator i = v.begin();  
        i != v.end(); ++i ) {  
    delete *i; // not exception safe  
}  
  
delete p;  
 ```

## Modern
```c
#include <memory>  
#include <vector>  
// ...  
// circle and shape are user-defined types  
auto p = make_shared<circle>( 42 );  
vector<shared_ptr<shape>> v = load_shapes();  
  
for_each( begin(v), end(v), [&]( const shared_ptr<shape>& s ) {  
    if( s && *s == *p )  
        cout << *s << " is a match\n";  
} );  
```

I also don't see any of that try catch stuff that seems to be rather popular in C++, which might make it easier to identify some errors on occasion: https://msdn.microsoft.com/en-us/library/6dekhbbc.aspx That's very different in the Android Java part of the code, which might be part of what I mean. When I think C++ I guess I expect to see something that looks more like complex Java to me than like C with additives.

**Pull request merged**
