### PR TITLE
Update French.pattern

### PR DESCRIPTION
**Pull request by cramoisi**
Hello there !
As requested by @poire-z, one change to deal with some rare cases of  l-l at the end of a line.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/553)

### CODE REVIEW

**Comment by poire-z** [comment]
Thanks !
Any thought about my previous "issue" with `neu-ros-ciences` at https://github.com/koreader/crengine/pull/157#issuecomment-946173478 ?

**Comment by cramoisi** [comment]
Yup I forgot this one. Will do it tomorrow :)

**Comment by cramoisi** [comment]
Yop,
I forgot how to add a change to an update :)

**Comment by poire-z** [comment]
Thanks!

> `<pattern>neu5ro5s6ciences</pattern>`

Not familiar with all things hyph patterns and how they work, but shouldn't we try to match for neuroscien* so to also do the right thing with `neuroscientifique` ?

**Comment by cramoisi** [comment]
Yup !

**Comment by poire-z** [comment]
Gentle ping :)
(My reading of "Les neuroscientifiques à l'époque de Churchill" is on hold since a few months ago, and I'm eager to finish it :)

**Comment by cramoisi** [comment]
that should do the trick.

**Comment by poire-z** [comment]
Thank you!

**Pull request merged**
