### PR TITLE
fix highlight position

### PR DESCRIPTION
**Pull request by frankyifei**

### CODE REVIEW

**Comment by houqp** [comment]
Since it's not used elsewhere, I still think it makes more sense to rename `bool ldomXRange::getRect( lvRect & rect )` to `bool ldomXRange::getRectEx( lvRect & rect )` so it's consistent with `bool ldomXPointer::getRectEx(lvRect & rect) const`. Should be a simple one line change. What do you think?

**Comment by frankyifei** [comment]
I am ok with that. but by doing that we substantially remove one function which exists in upstream. I'm not sure if that is good or bad.

**Comment by houqp** [comment]
I think as long as it's not used anywhere else then it should be fine. If upstream later decided to use the original function, we will get alerted by a compile time error, which is a good thing because we already changed the semantics of this function.

**Comment by houqp** [comment]
Thank you!

**Pull request merged**
