### PR TITLE
Fix ldomNode::getChildIndex() that could find wrong child

### PR DESCRIPTION
**Pull request by poire-z**
One Element node could be confused with another Text node.
It could cause the various functions related to finding a xpointer coordinates in the rendered document (that use `ldomXPointer::getRect()`) to find the wrong node and so the wrong coordinates.
`getRect()` first finds the rendered final block, and then iterates thru all its children text nodes to find the given xpointer. It could then stop on the wrong element node and return invalid coordinates.

Text nodes and Elements nodes use a different incremented counter for their index, and this bug could happen when we had them walking near each other when processing text and elements in some paragraph of the document (that's why it wasn't related in anything to the HTML tags or CSS styles, it was just chance, some coincidence in internal counters...). See comment in the code for details.

This was the reason for the wrong xpointer we got for link origin, that made me have to do #96.
So, after this, we shouldn't have anymore failure in 
```lua
--- Check if a xpointer to <a> node really points to itself
function ReaderLink:isXpointerCoherent(a_xpointer)
    [...]
    if re_a_xpointer ~= a_xpointer then
        logger.info("not coherent a_xpointer:", a_xpointer)
        return false
    end
    return true
end
```

It also solves some highlighting glitches that I used to have when selecting some text in a paragraph, with some parts of text italic, and some not italic, that happened often in some wikipedia epub.
While trying to reproduce it to make a screenshot, I happened to get this enormous glitch (still there when you restart koreader and open the page with this saved highlight):

<kbd>selection_messup</kbd>

After this fix, and restarting koreader, it becomes nice :

<kbd>selection_afterfix</kbd>

and live selection is now good too.

Here's some [debug log diff ](https://github.com/koreader/crengine/files/1785577/getChildIndex.diff.txt) of walking some paragraph (not the same as in screenshots above), before/after this fix.
Note that all Text node have even dataIndex, Element nodes have odd dataIndex.

We first meet a text node (dataIndex 8528, which is `/body/DocFragment/body/div/p[13]/text()[3]`), which is child 4 of the `/body/div/p[13]` we're walking:
```
        dataIndex: 8528
      child #4 of /body/DocFragment/body/div/p[13]
        dataIndex: 8289
      child #25 of /body/DocFragment/body/div
        dataIndex: 177
      child #4 of /body/DocFragment/body
        dataIndex: 65
      child #0 of /body/DocFragment
        dataIndex: 49
      child #0 of /body
        dataIndex: 33
      child #0 of
        dataIndex: 17
      child #0 of
   _indexes[0] = 0
   _indexes[1] = 0
   _indexes[2] = 0
   _indexes[3] = 0
   _indexes[4] = 4
   _indexes[5] = 25
   _indexes[6] = 4
   5 /body/DocFragment/body/div/p[13]/text()[3].0
```

And then we meet some other text node (dataIndex 8752, which is/body/DocFragment/body/div/p[13]/a[5]/text()), so, some link's text:
```diff
        dataIndex: 8752
      child #0 of /body/DocFragment/body/div/p[13]/a[5]
        dataIndex: 8529
-     child #4 of /body/DocFragment/body/div/p[13]
+     child #15 of /body/DocFragment/body/div/p[13]
        dataIndex: 8289
      child #25 of /body/DocFragment/body/div
        dataIndex: 177
      child #4 of /body/DocFragment/body
        dataIndex: 65
      child #0 of /body/DocFragment
        dataIndex: 49
      child #0 of /body
        dataIndex: 33
      child #0 of
        dataIndex: 17
      child #0 of
   _indexes[0] = 0
   _indexes[1] = 0
   _indexes[2] = 0
   _indexes[3] = 0
   _indexes[4] = 4
   _indexes[5] = 25
-  _indexes[6] = 4
+  _indexes[6] = 15
   _indexes[7] = 0
  19 /body/DocFragment/body/div/p[13]/a[5]/text().0 
```
While walking parents of `/body/DocFragment/body/div/p[13]/a[5]/text()`, we meet `/body/DocFragment/body/div/p[13]/a[5]`, whose dataIndex is 8529.
But `(8529 &= 0xFFFFFFF0) == (8528 &= 0xFFFFFFF0)`
So, the code was confusing it with 8528, and took it for the child 4, while it's actually child 15 of `/body/DocFragment/body/div/p[13]`

### CODE REVIEW

**Comment by Frenzie** [comment]
This sounds like it could be related to https://www.mobileread.com/forums/showthread.php?t=294938 ?

**Comment by poire-z** [comment]
Yes, looks like it (some italic among the text selected in both screenshots).

**Comment by Frenzie** [comment]
I explicitly checked for italic text though. No problems for me in the files I checked. :-)

**Comment by poire-z** [comment]
I think 1) is because of the hold area at bottom of screen being of higher priority to show the Go to page widget (I have personally disabled that because I don't use it, and I then can do dict lookup on words on last line - I think we can't have both :) may be `Hold on bottom to Go to page` could be made as an option?)

And 2) is because punctuation is used as the word separator, and so those on the edges are excluded. So of course, if he tries to select them, the only way to do that is to grab the next word (which may be on next paragraph, but that also happens in a single paragraph, where it would grab the first word of next sentence). Grabbing the previous or last puncutation/separator char, if it is not a space, to include it in selection would be a solution (risky and would  need testing, and I don't feel like revisiting #69), and would need more cleanup when doing dict lookup, to remove what we want to keep in highlights.

**Comment by Frenzie** [comment]
@poire-z I don't see `1` though, provided you start the selection high enough. Of course if you're in the go to page area you'll just trigger that instead. Maybe I misread the problem, but it sounds to me like the selection is succeeding but somehow the selection ends by not showing the selection popup.

Regarding `2` I honestly never even noticed that selecting the punctuation will auto-select the next line but it's easily reproducible. I like proper punctuation as much as the next guy but I wouldn't go out of my way to select it for a quick highlight. :-)

**Pull request merged**
