### PR TITLE
(Upstream) Various minor picks to keep some bits in sync

### PR DESCRIPTION
**Pull request by poire-z**
Picking what we can easily from https://github.com/buggins/coolreader/pull/304 and https://github.com/buggins/coolreader/pull/307:
- methods added to base objects, that can be helpful with future devs
- stuff that touches things we don't use (LVDrawBookCover, sentence selection fixes) and that git applied without much complain
- some easy cleanup.

Many other things not picked as they touch mostly the UI<->Core interface and we have already diverged too much, so even if I would have liked picking https://github.com/buggins/coolreader/commit/2d693aedd44c93 to keep much of that in sync, I didn't as we have diverged because of previous added things that we didn't need and I didn't picked at the time :/
Also, some top status bar refactoring that couldn't be integrated because we did some changes on our side, and upstream did too (ability to put this status bar at the bottom that we obviously didn't need, etc...)
So, well, that's how it is - with lvdocview.cpp having to be a bit of their version of our cre.cpp.

The LVDrawBookCover will need some fixes to cre.cpp, because we have its call in a method we don't use - so I'll comment out our drawCoverPage() and cursorRight().

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/450)

### CODE REVIEW

**Comment by poire-z** [comment]
@NiLuJe : any thoughts about https://github.com/koreader/crengine/pull/450#issuecomment-907043201 ?

**Comment by NiLuJe** [comment]
Haven't forgotten about it, but haven't had time to actually look into it yet ;p.

**Comment by poire-z** [comment]
Added 2 commits picked from https://github.com/buggins/coolreader/pull/308.

**Comment by poire-z** [comment]
Merging, as all is merged upstream.
I'll bump it after my next PR with small fixes.

**Comment by poire-z** [comment]
Pinging again @NiLuJe about https://github.com/koreader/crengine/pull/450#issuecomment-907043201 (still happening , ie in https://github.com/koreader/crengine/runs/4340698048?check_suite_focus=true)

**Comment by NiLuJe** [comment]
Last I checked it's because it's a class or something, but we tested the code on its own and it behaves, so, meh :/.

**Comment by poire-z** [comment]
But it's not a class, it's a classic struct. May be it's because the functions that use it are defined inside the stuct, so before it's fully defined?

> so, meh :/.

I know it behave, I'm just trying to (make you) kill introduced false positives so it doesn't bug us in CI output in unrelated PRs.

**Comment by poire-z** [comment]
> May be it's because the functions that use it are defined inside the stuct, so before it's fully defined?

Nope, that's not it.

**Comment by poire-z** [comment]
I can't even silence it with `// NOLINT` :/

https://stackoverflow.com/questions/49206519/not-able-to-use-offsetof-with-clang-compiler-using-libc-and-c14
(in case you understand anything to it :)

**Pull request merged**
