### PR TITLE
Upstream fix unused argument warnings

### PR DESCRIPTION
**Pull request by Frenzie**
@poire-z I had noticed these compiler warnings but it feels like a bit of a fake fix, doesn't it. :-P

### CODE REVIEW

**Comment by poire-z** [comment]
I haven't noticed any compiler warnings, but may be I didnt pay attention (or our build stuff is hiding them). But looks again like no-change, which I like :)

**Comment by Frenzie** [comment]
Generally the part that's compiled is also fairly small.

**Comment by frankyifei** [comment]
they are for clang originally I think

**Comment by Frenzie** [comment]
@frankyifei I definitely get various -Wunused-whatever in gcc. /shrugs

**Pull request merged**
