### PR TITLE
Add typography rules for Russian

### PR DESCRIPTION
**Pull request by dmalinovsky**
Russian typography prohibits having one and two letter words hanging at the end of the line.

There are many Russian resources discussing this, I've linked one of the better known ones.

If anyone knows if this is true for Ukrainian and Belarusian as well, please let me know.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/559)

### CODE REVIEW

**Comment by dmalinovsky** [comment]
@poire-z, can you please use this PR instead? My old one had a missing bracket — not sure how did it pass the checks...

**Comment by poire-z** [comment]
Oh, it's you who did this PR :)
I just fixed that (editing directly on Github web and commiting to master, first time for me), at the same time you made that PR :) Was worried I messed up :)

Your first PR is already merged, too late.
I fixed you error directly with https://github.com/koreader/crengine/commit/e498c1e4455567cea70a3c2b9e89ee736d25de16.

**Comment by dmalinovsky** [comment]
Thank you, @poire-z! I'll close this one then.

**Comment by poire-z** [comment]
I'm also removing a trailing space, which shows out in red in git console:
image

Fine with you if I also make your comments aesthetically aligned & consistent ?:
image

**Comment by dmalinovsky** [comment]
> Fine with you if I also make your comments aesthetically aligned & consistent ?:

Yes, please do. I made that PR in Github editor, and it wasn't the best idea.

**Pull request closed without merging**
