### PR TITLE
(Upstream) Adds ODT (ODF) format support

### LINKED ISSUE #367: ODF (odt) format support.
As the engine currently supports reading and displaying docx XML documents, I am surprised to find that it cannot open odt files.
Is odt support a thing that will be added?
It would be nice to support the Open formats for documents.
Thanks!

### PR DESCRIPTION
**Pull request by poire-z**
Adds support for ODT documents (OpenDocument Format), by @pkb, from:
https://github.com/buggins/coolreader/pull/164
https://github.com/buggins/coolreader/pull/165
https://github.com/buggins/coolreader/pull/168 (5th commit)

(I haven't digged into the code :/ I have just checked it works quite well :)

Closes #367.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/377)

### CODE REVIEW

**Comment by poire-z** [comment]
Regarding the [clang-tidy warnings](https://travis-ci.org/github/koreader/crengine/builds/726805238), we get 7 `Use of memory after it is freed` , all `~LVFastRef() { Release(); }` related.
Previously, we already had 3 of them (https://github.com/koreader/crengine/pull/351#issuecomment-653662559) so I'm not worrying.

@pkb: can you look at the 4 other warnings at https://app.codacy.com/manual/Frenzie/crengine_2/pullRequest?prid=6170911 , if they are negligible ?

**Review by Frenzie — APPROVED** [review]
Stick it in 2020.09 or wait for the next one?

**Comment by poire-z** [comment]
I'd rather wait :) I'll bump it with some other stuff after 2020.09 is done.

**Comment by pkb** [comment]
> 
> 
> @pkb: can you look at the 4 other warnings at https://app.codacy.com/manual/Frenzie/crengine_2/pullRequest?prid=6170911 , if they are negligible ?

I will not analyze if these are actual problem or not. It is just easier to fix them. Pleas apply [this](https://gist.github.com/pkb/8dd87d082d55827d59faf523e8c7fe6d) patch. Thanks.

**Comment by poire-z** [comment]
Thanks, looks good.
Codacy still complains about one thing that your patch fixed:
<kbd>image</kbd>
As I don't see what else might be missing, I guess it's just a mess up on their side with the diffs.

**Pull request merged**
