### PR TITLE
Fix yellow bgcolor on first launch

### PR DESCRIPTION
**Pull request by poire-z**
See https://github.com/koreader/koreader/pull/3353#issuecomment-336554217
(no need for bumps, this will go in with the next valuable commit)

### CODE REVIEW

**Comment by Frenzie** [comment]
I don't actually dislike the color in question. What I do dislike is the inconsistency. :-)

**Comment by poire-z** [comment]
I was actually fixing the inconsistency :) (even if I dislike the color :).
Anyway, if one would like a background color, there's this patch.lua solution till one implements it correctly in koreader: https://github.com/koreader/koreader/pull/3285#issuecomment-336090469

**Comment by Frenzie** [comment]
I didn't say I *liked* it. I'm ambivalent toward the color. But I do like the idea of a non-white background color on a backlit screen.

**Comment by Frenzie** [comment]
Btw, sticking it in base was unsatisfactory?

**Comment by poire-z** [comment]
Oh, I dunno, I didn't test it (but as anyway crengine itself saves it to cr3.ini as `background.color.default=0x00FFFFFF`, I guess explicitly doing that in base could may be not apply to first launch too).

**Comment by Frenzie** [comment]
But the defaults it saves come from https://github.com/koreader/koreader-base/blob/f0cad8faa0178f6543484e3477e4ef7e49bd02ea/cre.cpp#L315-L355 like I mentioned! Darn, thought you checked. :-P

**Comment by poire-z** [comment]
It's commented in the lines you mentionned :|
It most probably comes from:
https://github.com/koreader/crengine/blob/bb946cfafb4a6b8cd4d6063387b3ad4f202497da/crengine/src/lvdocview.cpp#L5502-L5521
So i was indeed fixing a crengine inconsistency :)

**Comment by Frenzie** [comment]
Yes, I explicitly mentioned that as the place to check for it. :-P

> Edit: it even has an override commented out for some reason https://github.com/koreader/koreader-base/blob/f0cad8faa0178f6543484e3477e4ef7e49bd02ea/cre.cpp#L325

I suppose it's a theoretical concern these days, but anything like this changed directly in crengine increases the forking distance.

**Comment by Frenzie** [comment]
@poire-z 

I didn't really notice it on the yellow but also the text is blue. :-P

screenshot_1508702912

**Comment by poire-z** [comment]
http://www.htmlcsscolor.com/hex/000060 I guess, just the line after the background one i changed...

**Pull request merged**
