### PR TITLE
Fix loading EPUBs containing XML files starting with the byte order mark (BOM)

### PR DESCRIPTION
**Pull request by newinnovations**
Fix for #448

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/449)

### CODE REVIEW

**Comment by poire-z** [comment]
Looks like `IsSpaceChar()` is used for other things in this lvxml.cpp, including when parsing further XML content and by `SkipSpaces()`, and as I'm not sure that any 0xFEFF found later among the XML should be discarded, I'd rather just hack it when it's needed. For example (untested):
```diff
--- a/crengine/src/lvxml.cpp
+++ b/crengine/src/lvxml.cpp
@@ -2887,6 +2887,7 @@ bool LVXMLParser::CheckFormat()
     chbuf[charsDecoded] = 0;
     bool res = false;
     if ( charsDecoded > 30 ) {
+        if ( chbuf[0] == 0xfeff ) chbuf[0] = ' '; // replace BOM with space
         lString32 s( chbuf, charsDecoded );
         res = s.pos("<FictionBook") >= 0;
         if ( s.pos("<?xml") >= 0 && s.pos("version=") >= 6 ) {
```

**Comment by newinnovations** [comment]
I think it is safe

> If the BOM character appears in the middle of a data stream, Unicode says it should be interpreted as a "zero-width non-breaking space" (inhibits line-breaking between word-glyphs). In Unicode 3.2, this usage is deprecated in favor of the "Word Joiner" character, U+2060.[1] This allows U+FEFF to be used only as a BOM.

Basically the BOM should only happen at the start, and if it happens elsewhere it should be handled as a space anyway.

**Comment by poire-z** [comment]
> Basically the BOM should only happen at the start, and if it happens elsewhere it should be handled as a space anyway.

We try to degrade nicely with stuff that _should not_ happen :)
Replacing any 0xFEFF with a space might be worse than keeping it, and it won't have it behave as a "zero-width non-breaking space".
Let the handling in other situations be buggy (attributes, `class="fooBOMbar"` is still better than getting `class="foo bar"` and matching 2 classnames) or handled just fine (like in text nodes, our text rendering stack, libunibreak and Harfbuzz may just handle it correctly as a "zero-width non-breaking space").

Well, I'd still prefer us to handle it for this specific need just where it's needed, in CheckFormat().

**Review by poire-z — APPROVED** [review]
Looks good to me.

**Comment by poire-z** [comment]
Tell us if you're in hurry to get this compiled for a device in a nightly build.
Otherwise, we'll wait a few days and/or some other fixes to bump it up to frontend.

**Comment by newinnovations** [comment]
I would like to see it appear in the kobo nightly as soon as possible. Thanks.

**Pull request merged**
