### PR TITLE
max/min-width/height: revise the computation

### PR DESCRIPTION
**Pull request by ourairquality**
The existing code was giving results inconsistent with chrome in some common cases. This PR tries to interpret the spec differently, making two passes computing the values, and for the examples tried it seems consistent with chrome, might be an improvement even if there are still some cases not handled correctly.

Here is one example. The image aspect ratio should be preserved in this case. This is a common usage for these constraints so it seems best to get them working a little better.

``````

There are still the cases in which both the width or height are 'auto', not handled yet. Shall take an look at these too, and might end up bundling that in here too but can be separate. This all seems like 'low hanging fruit' and nice to get working, very helpful for adaptive content.

Changed some of the calculations to use floats, the divisions, to get well rounded results, is that ok.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/414)

### CODE REVIEW

**Comment by ourairquality** [comment]
This is still not quite right. The case below is failing in some cases. Shall look into it. It is a little hard to interpret the spec when there are both height and width constraints, but it seems best to be consistent with chrome.

``````

**Comment by ourairquality** [comment]
Updated to passes more tests. It seemed necessary to specially handle the case in which both width and height constraints were invoked, retrying with just one constrained to try to maintain the aspect ratio, but if that fails then it is over constrained and the aspect ratio can not be maintained.

Also noticed that there is already code there to handle the case in which both the width and height are 'auto'. So that is all the issues spotted there for now.

**Comment by poire-z** [comment]
Note that I've done all my tests and comparisons with Firefox, and very rarely compared with Chrome.
So, please also check with Firefox before assuming it's an error and going at fixing it. If there's differences between how Chrome and Firefox do, we have to discuss it and make a choice.

Tested this PR with the [test file I ended up when doing min/max-stuff](https://github.com/koreader/crengine/files/5897737/test-min-max-width-height.zip), and there are some bugs: extremely tall images. The yellow stars inline images which is what I wondered about first are ok.

Firefox:
<kbd>image</kbd>
KOReader did all similar before this PR.

With this PR, the 2nd and 3rd images makes the book 121 pages
<kbd>image</kbd>

<kbd>image</kbd>

(Haven't yet read your code, that's the kind of x/y/w/h code I don't really enjoy doing or reading :)

**Comment by poire-z** [comment]
About the code, I think I initially went intuitively with ensuring A/R like may be you are doing. But I didn't get the same results as Firefox. Looked at some other implementation (WeasyPrint, in python), which seems to go at doing everthing width first, and then height (as the specs say if you accept that it's not really intuitive and feels not the best), and I got what Firefox shows. So the simple code you saw.
I don't mind you tweaking that to make it more intuitive/expected and fixing some other cases, as long as my tests still show as Firefox (which they do on the yellow star images for now).
(But the specs really seem to indicate: do it that simple, don't overthink it :)

About the code itself:
- please use float instead of double to please @NiLuJe :) See https://github.com/koreader/crengine/pull/410#discussion_r563863109.
I think there was nearly no float computation in crengine (although I see I have introduced one with my `2.54` in lengthToPx()), so don't abuse them if not needed, as we may target devices that could be better with just integer arithmetic.
- personally, I have a hard time reading your style of else:  `} else {` - I see you can still use _my_ style
```
}
else {
```
 in part of the code you updated. So, if you're fluent with both, please keep using mine - or at least try to stay consistent with the surrounding style in the parts of code you're updating. Thanks.

**Comment by Frenzie** [comment]
> Note that I've done all my tests and comparisons with Firefox, and very rarely compared with Chrome.
So, please also check with Firefox before assuming it's an error and going at fixing it. If there's differences between how Chrome and Firefox do, we have to discuss it and make a choice.

For the moment I'll spare you guys my spiel regarding my approach to the spec and its implementations, but I'm not consciously aware of any real differences between Chromium and Firefox wrt min-*/max-* stuff in the present day? It's not the year 2000 anymore, although actually crengine's brand new support is not dissimilar to the initial support in Opera 4. (I think its interaction with tables was undefined by the spec itself at the time, but that's pretty much the same underlying reason.)

**Comment by Frenzie** [comment]
> About the code, I think I initially went intuitively with ensuring A/R like may be you are doing. But I didn't get the same results as Firefox. Looked at some other implementation (WeasyPrint, in python), which seems to go at doing everthing width first, and then height (as the specs say if you accept that it's not really intuitive and feels not the best), and I got what Firefox shows. So the simple code you saw.

Actually with this new comment I think my spiel is warranted.

I look at the spec, Firefox, Prince, WebKit, Chromium, and for good measure oftentimes also IE/old Edge/old Opera (because Presto is outstanding). When in doubt, that is. Also I like to look at the older CSS 1/2/2.1 specs if something's a bit unclear, because the present-day spec can be quite hard to understand due to all the little edge cases. Which is good to specify of course, but it makes it harder to grasp the general idea. The edge cases only matter once you have the basics down.

Also, as a rule of thumb, imo if there's a deviation then Chrome is probably wrong. All bugs I've reported were ignored or misunderstood by Google people but luckily fixed by Intel years later (yes, Intel). By contrast, in Firefox they might also not fix it but at least they'll have what sounds like a good reason (i.e., technically very complex to do, as opposed to what basically comes down to "I can't be bothered to read properly.") As a consequence I distrust Chromium. Incidentally, Chromium also proudly maintains many old WebKit bugs that *WebKit has since fixed*.

Prince is just excellent, and any potential deviations/proprietary extensions for optimal page-based display are very well thought out. As far as I'm concerned Prince and Firefox are the reference implementations to follow.

**Comment by ourairquality** [comment]
Thank you for sharing the test cases. I had introduced a one line error which has been corrected and the output seems more plausible now. I also retried my own tests in Firefox and it gave the same results as Chrome. When I suggested following chrome, I meant follow the main web browsers - did not want to start a browser war.

The following examples might demonstrate the errors or limitations in the current code and why this revision is proposed. These appear to behave the same in Chrome and Firefox, both maintain the aspect ratio is possible when both width and height constrains are invoked.

```
<img src="..."  style="height: 20em; max-height: 50vh; max-width: 50vw;" />

<img src="..."  style="width: 20em; max-height: 50vh; max-width: 50vw;"  />

<img src="..."  style="width: 20em; min-height: 50vh; min-width: 50vw;"  />
```



I might take a look at adding support for the object-fit property as it is part of this set of features and modifies the algorithms in some cases, and it might be usable to maintain the aspect ratio which is likely a common use:

https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

**Comment by poire-z** [comment]
> The following examples might demonstrate the errors or limitations in the current code and why this revision is proposed

Just took your examples, and replaced the new units with em. Seems the current master (without this PR) shows as Firefox (on the left - KOReader on the right):
<kbd>image</kbd>

Haven't yet tested with this PR and vh/vm, but would vh/vw exhibit a different behaviour from what I got with em? (Just asking, haven't think much about that :)

**Comment by ourairquality** [comment]
The viewport units certainly help testing this as you can modify the computed pixel values by changing the window size to see the transitions and then issues become obvious. I particular look for the aspect ratio being maintained with the revision where it is not currently. The same can be done in Firefox by changing the windows size, perhaps give that a try to see the transitions. Chrome has a developer tool that is supposed to help test responsive designs but it seems broken, so just scale the window there. Firefox has a responsive design aid too that seems more useful, but it in doubt scale the window.

**Comment by Frenzie** [comment]
> I might take a look at adding support for the object-fit property as it is part of this set of features and modifies the algorithms in some cases, and it might be usable to maintain the aspect ratio which is likely a common use:

As an aside, there might potentially be some overlap with the newer background-size attributes? (Like contain and cover.)

**Comment by NiLuJe** [comment]
Sidebar on the float aspect: Is there any actual gains in using a precise division with floats... and then letting it be truncated by a cast?

If you go the float way, I'd do it *all the way*: e.g., `iroundf` the result instead of letting it be trunctaed by a cast ;).

**Comment by poire-z** [comment]
Firefox on the left | KOReader with #413 but **without #414**:
Same viewports, large width:

image

image

Same viewports, small width (as small that Firefox allows):
image

image

I don't see much differences with various kind of images, but I did notice once a difference, that I can't find anymore.

----
Firefox on the left | KOReader with #413 but **with #414**:

image

There are differences in the axis that we don't see above.
It's usually as fine, but I see more differences with #414 than without. Mostly for the 2nd one in the set, the one that start with `width:`.

I'm a bit upset having spend two hours on your vague examples and _perhaps give that a try to see the transitions_: I see the transitions, but I don't see the bugs :/ (and it's hell testing transitions and having to resize KOReader to match Firefox viewport).
I tested this with the Lac and star.png, and the differences were more obvious than with my stupid aspect ratio image... But I'm fed up with this, so not remaking screenshots.
May be you tested with some other kind of image ratio/size, with some other browser geometry... but I don't want to guess.

So, rather than trying to be convinced by your patch, please convince me there's an issue with current crengine after #413 - I know there might be one I saw a difference, I just can't find it again.

Please provide a test HTML + the image you test with (so I get the same aspect ratio you test with), **and** screenshots of KOReader **before**, KOReader **after** #414, **and** Firefox **and** Chrome.
And if you show me one obvious and your patch is valid, try to see the issue with #414 and your 2nd sample starting with `width:` - I witnessed this one quite often.

Not convinced for now.

**Comment by poire-z** [comment]
> If you go the float way

I'd rather see `*1000 ... / 1000` like  there are all along crengine, than see `(float)` as there's currently zero of that. But that's just because I'm used to see that - and I don't think the clever crengine original author was dumb enough to not use floats, so he must have had a reason.

The only 2 float usage I found were from me without much thinking :):
```
unsigned char * convertSVGtoPNG(const unsigned char *svg_data, int svg_data_size, float zoom_factor, int *png_data_len)
static float _storageMaxUncompressedSizeFactor = 1;
and may be my 2.54 in lengthToPx().
```

**Comment by NiLuJe** [comment]
That was probably a very conscious decision because it originally targeted devices without an FPU at all ;).

**Comment by Frenzie** [comment]
@poire-z Your height 5vm width 10vw looks a bit distorted.

I agree the issue is very vague. Please try to include minimal testcases as well as screenshots. :-)

**Comment by ourairquality** [comment]
Here is an example that appears to demonstrate an issue with the current code. Try adding this to your updated test files, that reproduced it for me. Notice that the aspect ratio is preserved in Firefox and with the change proposed here, but not with the existing code.

``````

Yes, I'll use px in future examples. I should save examples of issues I notice in passing too, in px - it took me some time to find an example again! I hope you can reproduce it simply enough being in px, just adding it to your example.

I am happy to keep to integer calculations, and have reworked my local files to do that. Lets keep that for another PR. It escaped me that C truncates floats when implicitly casting to integers, sorry, and that is all removed that from this PR.

**Comment by poire-z** [comment]
Thanks, that's a quite obvious example :)
Re-reading the specs, I see nothing that backs your way of solving this (that I have a hard time getting into), intervening min/max-width and min/max-height computations.

The only thing the current code doesn't do according to the specs is going back recomputing the width once we have ensured max/min-height - but only for height. You seem to do it also for width. May be that's the reason for the little differences I found with this PR and stuff starting with `width:`.
Ensuring this part of the specs with just:
```diff
--- a/crengine/src/lvrend.cpp
+++ b/crengine/src/lvrend.cpp
@@ -2596,6 +2596,28 @@ bool getStyledImageSize( ldomNode * enode, int & img_width, int & img_height, in
         // Ensure heights constraints
-        if ( max_height >= 0 && h > max_height)
+        // https://www.w3.org/TR/CSS21/visudet.html#min-max-heights says that when
+        // ensuring the height constraints, "the rules above are applied again",
+        // meaning the previous width adjustment should be done again with the
+        // computed height.
+        // This comes down to, when no width specified, recompute the width to
+        // keep aspect ratio, and ensure min/max width on the recomputed width.
+        if ( max_height >= 0 && h > max_height) {
             h = max_height;
-        if ( h < min_height )
+            if ( width < 0 ) {
+                w = h * native_width / native_height;
+                if ( max_width >= 0 && w > max_width)
+                    w = max_width;
+                if ( w < min_width )
+                    w = min_width;
+            }
+        }
+        if ( h < min_height ) {
             h = min_height;
+            if ( width < 0 ) {
+                w = h * native_width / native_height;
+                if ( max_width >= 0 && w > max_width)
+                    w = max_width;
+                if ( w < min_width )
+                    w = min_width;
+            }
+        }
     }
```
seems to solve your obvious example - and doing it more according to the specs (I think).

Thoughts? Could you check how this does on your other test cases?

**Comment by poire-z** [comment]
I included [my above quick fix](https://github.com/koreader/crengine/pull/414#issuecomment-770356529) in https://github.com/koreader/crengine/pull/416.
We can still discuss bugs and other options here if it happens to be bad or not enough.

**Comment by ourairquality** [comment]
Ok, thanks. There are a lot of combinations on this path to check and it was not immediately obvious, but shall work through them to double check eventually, but it's probably good now, or any failing cases are not common.

**Pull request closed without merging**
