### PR TITLE
Better font debugging

### PR DESCRIPTION
**Pull request by Frenzie**

### CODE REVIEW

**Comment by poire-z** [comment]
Btw, how does one turn on these CRLog::debug & others ?
I usually replace the ones i need with a `printf(...\n)` ...

**Comment by Frenzie** [comment]
> I usually replace the ones i need with a printf(...\n) ...

That's what I do. */me whistles*

But the answer lies here:

https://github.com/koreader/koreader-base/blob/680c9f9b9454144b4233214996c6664bf0c59aac/cre.cpp#L1668-L1671

> And what's that CR_UNUSED() for ?

That's just some crengine thing. Doubtless a horrible practice. :-P

https://github.com/koreader/crengine/blob/a09aac18672f5f9c57d87457afbac205001ed793/crengine/include/lvtypes.h#L384

**Comment by poire-z** [comment]
Thanks!
(But why did you think about adding that CR_UNUSED() there ? Got some warning somewhere?)

**Comment by Frenzie** [comment]
It's not really my patch, but backported from https://sourceforge.net/p/crengine/crengine/ci/8c734fcb859859a79755511fbe1af5b7572298d0/ after I couldn't find one of the lvfntman or lvrend change I was missing iirc. Where by couldn't find I mean within a few minutes, so I also checked upstream and this is pretty much the only relevant improvement that's been made there. ;-)

A couple of hours ago [this comment](https://www.mobileread.com/forums/showthread.php?p=3655038#post3655038) reminded me I already had branches with fixes lying around, so I immediately tossed them out on GH. I guess I created them during spring vacation last year when I had a tiny bit of time, after which I was rather busy for several months. Then I skimmed through the issue and realized I hadn't included all of the relevant changes for some reason, probably 'cause it was faster to test that way.

**Comment by Frenzie** [comment]
Btw, that crengine debug can be quite noisy depending on the document.

**Pull request merged**
