### PR TITLE
Add support for MathML

### PR DESCRIPTION
**Pull request by poire-z**
Months of work since https://github.com/koreader/koreader/issues/6346#issuecomment-653774141 and https://github.com/koreader/koreader/issues/6678#issuecomment-695178895.
And I don't even read math stuff... My Mathematic is just a little bit better than my Arabic - at least, I can spell maths :) 
I started it with the [CSS solution](https://www.w3.org/TR/mathml-for-css/), and thought it would just need a little help from the code to get better - but the more I tested, the more I saw ugly stuff, the more I needed to have them look at least ok, the more code work it became.
Some screenshots in next post.

----
(From the top of mathml.cpp:)

MathML specific DOM building and rendering code

Main references:
 https://www.w3.org/TR/MathML/ MathML Version 3.0 (2014)
 https://www.w3.org/TR/MathML2/ MathML Version 2.0 (2003)

 https://mathml-refresh.github.io/mathml-core/
 https://github.com/mathml-refresh/mathml
   "This specification defines a core subset of Mathematical Markup Language, or MathML, that is suitable for browser implementation [...] being as accurate as possible on the visual rendering of mathematical formulas."

Other related informations and discussions:
 https://www.w3.org/Math/testsuite/
 http://fred-wang.github.io/AcidTestsMathML/acid3/description.html
 http://www.unicode.org/reports/tr25/ Unicode support for mathematics
 https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols

Additional CSS tweaks by some implementations
 https://github.com/WebKit/WebKit/blob/main/Source/WebCore/css/mathml.css
 https://searchfox.org/mozilla-central/source/layout/mathml/mathml.css#16

Some attemps at supporting MathML via CSS only, that we took some bits from:
 https://www.w3.org/TR/mathml-for-css/
 https://github.com/fred-wang/mathml.css

Harfbuzz OT math support:
 `https://github.com/harfbuzz/harfbuzz/issues/235`
 `https://github.com/harfbuzz/harfbuzz/issues/2585`
Harfbuzz code (not merged) to properly shape/draw stretchy operators:
 https://github.com/fred-wang/harfbuzz/tree/MATH-3
 https://frederic-wang.fr/opentype-math-in-harfbuzz.html

Math fonts:
 https://tex.stackexchange.com/questions/425098/which-opentype-math-fonts-are-available
 https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/Fonts
 http://fred-wang.github.io/MathFonts/
 https://docs.microsoft.com/en-us/typography/opentype/otspec183/math

Other implementations:
In rust:
 https://github.com/manuel-rhdt/mlayout/blob/master/src/typesetting/shaper.rs
Firefox:
 https://github.com/mozilla/gecko-dev/tree/master/layout/mathml
 https://github.com/mozilla/gecko-dev/blob/master/layout/mathml/nsMathMLmoFrame.cpp
 https://github.com/mozilla/gecko-dev/blob/master/layout/mathml/nsMathMLChar.cpp
 https://github.com/mozilla/gecko-dev/blob/master/gfx/thebes/gfxFT2Utils.cpp font metrics
Chromium:
 https://mathml.igalia.com/project/
MathJax:
 https://github.com/mathjax/MathJax-src/blob/master/ts/core/MmlTree/OperatorDictionary.ts
 https://github.com/mathjax/MathJax-src/blob/master/ts/core/MmlTree/MmlNodes/mo.ts

How various implementations render `<mover>` with accent or not...:
 `https://github.com/mathml-refresh/mathml/issues/210#issuecomment-700367434
`
What's currently supported by our implementation:
- Simple grouping `<math>` (with its display attribute), `<mrow>`, `<mstyle>`, `<merror>`, `<mpadded>`, `<mphantom>` (with visibility: hidden), `<menclose>`, but only a small set of their attributes (mostly handled via CSS).
- Simple text containers: `<mi>`, `<mn>`, `<mo>`, `<mtext>` and `<ms>`, with support for the mathvariant attribute (and italic'ing of `<mi>` with a single char), mathsize, mathcolor, mathbackground.
- Fraction `<mfrac>`, with linethickness zero and non-zero.
- Roots `<msqrt>` and `<mroot>`.
- Postscripts: `<msub>`, `<msup>`, `<msubsup>`.
- Multiple pre and post scripts: `<mmultiscripts>`.
- Under and over scripts: `<munder>`, `<mover>`, `<munderover>`.
- Basic HTML-like implementation of `<mtable>`.
- `<mspace>`, very limited support for `<mpadded>`
- `<mo>` and embelished operators, via operator dictionary or attributes: support for 'form', 'largeop', 'movablelimits', 'accent' (and the 'accent' and 'accentunder' attributes on `<munderover>`), 'stretchy', 'symmetric', 'minsize' and 'maxsize'. 'lspace' and 'rspace' (forwarded to the sides of an upper embelished container).
- Scaling of largeop and stretchy operators (but not using the font OT math variants nor shaping with multiple glyphs).
- Support of length attributes with classic CSS units, and with namedspaces ("thinmathspace"...)

Current limitations:
- Some rare MathML elements are not handled in any specific way (at most, by some simple styling via CSS), mostly those not mentionned in the mathml-core spec: `<menclosed>`, `<mstack>` (and its inner elements), `<mlongdiv>` (and its inner elements).
- Many attributes mentionned in the MathML spec (very few of them are mentionned in the mathml-core spec) are not handled at all (none for `<mstyle>`, few for `<mpadded>`, only those for `<mtable>` that are named the same for HTML `<table>`, ...)
- Especially, some fine positionning in elements we otherwise support well are not (like `<msuper superscriptshift=...>`).
- No specific linebreaks handling: stuff might be wrapped inside inline-blocks that we abuse for rendering.
- Balanced strechy operators may have their heights unbalanced if they and their inner content happen to wrap onto 2 text lines.
- Because of the way vertical stretchy operators are handled (adjusting to the erm_final line containing them), 2 independant inline `<math>` elements on a same text line can have their stretchy operators get the same height, so not adjusting to the height of their inner content... (note that Firefox does not stretch a `<mo>`, while MathJax does, when it's a direct child of an inline `<math>` but it does when there is a `<mrow>` in between (may be to avoid having our behaviour?)
- Simple handling of stretchy operators by just scaling the glyph (using OpenType math features to build a composition from multiply glyphs is not implemented).
- The drawing of the `<msqrt>` and `<mroot>` symbols is not handled as per the mathml-core specs (fine positionning via the font OT math metric, using a the radical symbol glyph of the font), but is done via table borders and a background SVG image.

----
Commits:

#### Images: allow ``

In `img src="..."` and `background-image: url(...)`, where we support `data:image/svg;base64,...`, also support a non-standard `data:image/svg;-cr-plain,...`.
May be used to build SVG images at rendering time, and have the code set them as attribute or styles (will be useful to generate the MathML `<msqrt>` radical symbol).

#### CSS: properly handle selectors with internal boxing element names

When checking selectors, we normally skip/enter/exit internal boxing elements when waking parents or siblings.
This allows having selectors specifying one type of internal boxing elements - and so not skip them.
Adds in advance a new internal elements: <mathBox>, which will be used for MathML support (which will use CSS selectors to do some part of its work).

#### CSS ensure width on boxing element table sub-elements

As only us (and not publishers) can set widths on them, ensure them even if we normally don't on table sub-elements.

#### MathML: adds LVInkMeasurementDrawBuf

Allows measuring the area taken by ink (glyphs, borders, images...) by just using the regular drawing code.
(Easier than doing it using font and glyphs metrics...)

#### MathML: Fonts: allow drawing stretched glyphs

Simple (and ugly) way to draw MathML stretchy operators, for fences, arrows, ... to adjust to their neighbours.
A more correct rendering would require more changes here and in lvtextfm.cpp, to use OT Math fonts glyph variants and glyph construction features.

#### MathML: plug MathML code into crengine core

Everything wrapped in `#if MATHML_SUPPORT==1 / #endif`, mostly for documentation purpose, to make it explicite a reader can skip it when not interested.

lvtinydom.cpp DOM writers: add flag when entering `<math>`, so that MathMLHelper can complete and tweak the DOM as it is being built.

lvrend.cpp: as most of the non trivial MathML elements (mfrac, msub, mover, msqrt...) are handled as inline-table, plug a few specific handler in the table rendering code, and in `getRenderedWidths()` to estimate inline-block/table elements min/max widths.
Also have `setNodeStyle()` call `setMathMLElementNodeStyle()` on MathML elements to complete their styling.

lvtextfm.cpp: alignLine() position inline-block boxes may call a specific method on MathML elements to tweak their position and size to ensure vertical stretching of MathML operators, so they adjust to the line box vertical space, adjusting the line height and baseline.

lvrend.cpp `renderFinalBlock()` and lvtextfm.cpp: pass LTEXT_MATH_TRANSFORM flag to have stretchy final blocks drawn stretched.

#### MathML: `<epub:switch/case/default>`: accept MathML

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/429)

### CODE REVIEW

**Comment by poire-z** [comment]
Some screenshots of http://fred-wang.github.io/mathml.css/, with various OpenType Math fonts.

FreeSerif (which IS a Math font, and pretty good):
<kbd>image</kbd>

Latin Modern Math:
<kbd>image</kbd>

Libertinus Serif Math:
<kbd>image</kbd>

STIX Two Math:
<kbd>image</kbd>

From the book Probability and Statistics.epub shown at https://github.com/koreader/koreader/issues/4381 (seems no longer available at the d/l url in there):

<kbd>image</kbd>

and ... just noticing this glitch in here :( ; 
<kbd>image</kbd>

The EPUB3 linear algebra book from https://idpf.github.io/epub3-samples/30/samples.html works quite less well, as it has many thing wrapped in `<mtable>` with blank columns reducing the available space, so many bad wraps :
<kbd>image</kbd>

Another quite noticable thing, the way we stretch fences, not using MathML constructions, but just stretching the normal glyph : 
<kbd>image</kbd>

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/koreader/crengine/429)* status: all files reviewed, 7 unresolved discussions (waiting on @poire-z)

___
*[crengine/include/lvdrawbuf.h, line 609 at r1](https://reviewable.io/reviews/koreader/crengine/429#-MW5ms1203q0XRMeKCit:-MW5ms1203q0XRMeKCiu:bgn1ozw) ([raw file](https://github.com/koreader/crengine/blob/616c92dbd3c5e337fabe06a0f61d99a6f5ce7658/crengine/include/lvdrawbuf.h#L609)):*
> ```objc
>     virtual void Draw( int x, int y, const lUInt8 * bitmap, int width, int height, const lUInt32 * __restrict palette ) {
>         // printf("  ink Draw %d %d %d %d\n", x, y, width, height);
>         // Used to draw glyph. Trust the font that the bitmap is the glyph blackbox, so its ink area
> ```

Did you mean boundingbox?
___
*[crengine/include/lvfntman.h, line 217 at r1](https://reviewable.io/reviews/koreader/crengine/429#-MW5nFOkAGoWMAmrbU55:-MW5nFOkAGoWMAmrbU56:b-siolbr) ([raw file](https://github.com/koreader/crengine/blob/616c92dbd3c5e337fabe06a0f61d99a6f5ce7658/crengine/include/lvfntman.h#L217)):*
> ```objc
> #define LFNT_HINT_IS_FALLBACK_FONT       0x0010 /// set on recursive Harfbuzz rendering/drawing with a fallback font
> 
> #define LFNT_HINT_TRANSFORM_STRETCH      0x0100 /// Glyph(s) are to be stretched so their blackbox fit the provided w/h
> ```

Ditto ;)
___
*[crengine/src/lvfntman.cpp, line 3053 at r1](https://reviewable.io/reviews/koreader/crengine/429#-MW5pBRR6-vUwdxuLd0k:-MW5pBRR6-vUwdxuLd0l:b-v0va8r) ([raw file](https://github.com/koreader/crengine/blob/616c92dbd3c5e337fabe06a0f61d99a6f5ce7658/crengine/src/lvfntman.cpp#L3053)):*
> ```cpp
>                 // Defaults to 0
>                 break;
> ```

Random LF or intended?
___
*[crengine/src/lvfntman.cpp, line 3695 at r1](https://reviewable.io/reviews/koreader/crengine/429#-MW5pwaB4J28LSKWCadv:-MW5pwaB4J28LSKWCadw:bi7nnlk) ([raw file](https://github.com/koreader/crengine/blob/616c92dbd3c5e337fabe06a0f61d99a6f5ce7658/crengine/src/lvfntman.cpp#L3695)):*
> ```cpp
>         }
> 
>         if ( glyph.width == 0 || glyph.blackBoxY == 0 ) {
> ```

Ah, now I see that the weird name is yet another CRe-ism (possibly inherited from legacy Win32 code?) ^^.

oh, well. ;).
___
*[crengine/src/lvfntman.cpp, line 3718 at r1](https://reviewable.io/reviews/koreader/crengine/429#-MW5qH8l5UeasAOUf_NE:-MW5qH8l5UeasAOUf_NF:b-hyvhcw) ([raw file](https://github.com/koreader/crengine/blob/616c92dbd3c5e337fabe06a0f61d99a6f5ce7658/crengine/src/lvfntman.cpp#L3718)):*
> ```cpp
>         int scale_y = target_h * 256 / glyph.blackBoxY;
> 
>         // Hijack pixel size to let FreeType scale the glyph to our target size
> ```

I'm not familiar with the API, but IIRC, FT has matrix transform functions to do that sort of thing?
___
*[crengine/src/lvtextfm.cpp, line 2375 at r1](https://reviewable.io/reviews/koreader/crengine/429#-MW6AvjA1ZKjau0HdFFH:-MW6AvjA1ZKjau0HdFFI:bmjjlad) ([raw file](https://github.com/koreader/crengine/blob/616c92dbd3c5e337fabe06a0f61d99a6f5ce7658/crengine/src/lvtextfm.cpp#L2375)):*
> ```cpp
>                     fmt.push();
>                     #if MATHML_SUPPORT==1
> 			ldomNode * unboxedParent = node->getUnboxedParent();
> ```

Stray tabs?
___
*[crengine/src/mathml.cpp, line 1208 at r1](https://reviewable.io/reviews/koreader/crengine/429#-MW6DfXZ7TrNrdTVh0KH:-MW6DfXZ7TrNrdTVh0KI:b-bhaxfv) ([raw file](https://github.com/koreader/crengine/blob/616c92dbd3c5e337fabe06a0f61d99a6f5ce7658/crengine/src/mathml.cpp#L1208)):*
> ```cpp
>     if ( accept_namedspaces ) {
>         int ratio = 0;
> 	if ( value[0] == U'v' ) {
> ```

Stray tab ;)

**Comment by NiLuJe** [comment]
This... must have been "fun"... Kudos ;).

**Review by Frenzie — COMMENTED** [review]
> Reviewed 9 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/koreader/crengine/429)* status: 10 of 17 files reviewed, 8 unresolved discussions (waiting on @NiLuJe and @poire-z)

___
*[crengine/include/lvdrawbuf.h, line 656 at r3](https://reviewable.io/reviews/koreader/crengine/429#-MW6QZbc5uAQ3K5rynBN:-MW6QZbc5uAQ3K5rynBO:bet5xhi) ([raw file](https://github.com/koreader/crengine/blob/379127837e495269426e78a5b6350a4da0c491b1/crengine/include/lvdrawbuf.h#L656)):*
> ```objc
>     virtual void DrawOnTop( LVDrawBuf * __restrict buf, int x, int y) {}
>     virtual void DrawRescaled(const LVDrawBuf * __restrict src, int x, int y, int dx, int dy, int options) {}
> #if !defined(__SYMBIAN32__) && defined(_WIN32) && !defined(QT_GL)
> ```

This is just copied from elsewhere?

**Comment by NiLuJe** [comment]
> > Reviewed 9 of 16 files at r3.
> > _[Reviewable](https://reviewable.io/reviews/koreader/crengine/429)_ status: 10 of 17 files reviewed, 8 unresolved discussions (waiting on @NiLuJe and @poire-z)
> 
> _[crengine/include/lvdrawbuf.h, line 656 at r3](https://reviewable.io/reviews/koreader/crengine/429#-MW6QZbc5uAQ3K5rynBN:-MW6QZbc5uAQ3K5rynBO:bet5xhi) ([raw file](https://github.com/koreader/crengine/blob/379127837e495269426e78a5b6350a4da0c491b1/crengine/include/lvdrawbuf.h#L656)):_
> 
> > ```objc
> >     virtual void DrawOnTop( LVDrawBuf * __restrict buf, int x, int y) {}
> >     virtual void DrawRescaled(const LVDrawBuf * __restrict src, int x, int y, int dx, int dy, int options) {}
> > #if !defined(__SYMBIAN32__) && defined(_WIN32) && !defined(QT_GL)
> > ```
> 
> This is just copied from elsewhere?

Yeah, that's the standard "signature" for a *DrawBuf class ;).

**Comment by poire-z** [comment]
Adressed the above review comments.
Fixed some CI warnings (LVBitmapFont, undefined function argument).
Fixed my above fraction glitch: the ink measurement stuff got a `y=-2147483639` :)  because in my DrawStretchedGlyph, I was removing 2px padding from something that measured only 1px... So, added some checks to avoid getting negative, and removed the padding when horizontally stretching, so we see a bit more of the `~ - ^` that can get really thin:
<kbd>image</kbd>

> I'm not familiar with the API, but IIRC, FT has matrix transform functions to do that sort of thing?

May be, could have worked (crengine used to use FT_Set_Transform for fake italic, but I switched it to use FT_GlyphSlot_Oblique - so may be that Transform could be used - unless there's conflict with the other hidden stuff. Anyway, I'm a bit fed up with maths, so I won't go look at FreeType Matrix stuff :)
https://www.freetype.org/freetype2/docs/tutorial/step1.html
Hopefully, changeing the pixel size should do the same kind of math internally that this straight linear transform.
> This is just copied from elsewhere?

Yes, from the similar sections in the other *DrawBuf (the function accepts a "HDC" struct that must come from windows.h).

**Comment by NiLuJe** [comment]
Fair enough, just thought I'd mention it because it seemed vaguely related from whatever I remembered from a cusrosry glance at FT's API docs a few years back ;o).

**Comment by poire-z** [comment]
Merging, as I haven't touched it for 2 days, which is a first :) This means it's pretty stable !
I'll bump it in a few days.
For those curious, it needs this patch to base to compile:
```diff
--- a/Makefile.defs
+++ b/Makefile.defs
@@ -708,2 +708,4 @@ CRENGINE_SRC_FILES=$(wildcard $(CRENGINE_SRC_DIR)/crengine/src/*.cpp)
 CRENGINE_SRC_FILES+=$(wildcard $(CRENGINE_SRC_DIR)/crengine/include/*.h)
+CRENGINE_SRC_FILES+=$(wildcard $(CRENGINE_SRC_DIR)/crengine/src/*.h)
+CRENGINE_SRC_FILES+=$(wildcard $(CRENGINE_SRC_DIR)/crengine/src/*_h.*)
 CRENGINE_LIB=$(OUTPUT_DIR)/libs/libcrengine$(LIB_EXT)
--- a/thirdparty/kpvcrlib/CMakeLists.txt
+++ b/thirdparty/kpvcrlib/CMakeLists.txt
@@ -68,2 +68,3 @@ add_definitions(
     -DCR3_PATCH=1
+    -DMATHML_SUPPORT=1
 )
@@ -165,2 +166,3 @@ set (CRENGINE_SOURCES
     ${CRE_DIR}/src/lvrend.cpp
+    ${CRE_DIR}/src/mathml.cpp
     ${CRE_DIR}/src/wolutil.cpp
```

**Pull request merged**
