### PR TITLE
dealing with cyber- words

### PR DESCRIPTION
**Pull request by cramoisi**
```
<pattern> cy1be2r1</pattern>
<pattern> cybera2</pattern>
<pattern> cybere2</pattern>
<pattern> cyberé2</pattern>
<pattern> cyber3h2</pattern>
<pattern> cyberi2</pattern>
<pattern> cybers2</pattern>
<pattern> cybe3rien</pattern>
```

### CODE REVIEW

**Comment by cramoisi** [comment]
as discussed [here](https://github.com/koreader/crengine/pull/157#issuecomment-493590825) and below

**Comment by poire-z** [comment]
Thanks.
(Waiting a few days before merge & bump, in case you feel like adding more patterns for other things.)

**Comment by cramoisi** [comment]
These last rules are dealing with everything I've added locally since the 20180704 update so I guess it's good for now. Perhaps I need to read more SF with no standard words to find new exceptions :)

**Comment by cramoisi** [comment]
@poire-z  : I don't know why but the short rules I introduced in the last commit don't work (ie : on "grands" , I got "grand-s") and I can't understand why so I'll revert.

**Comment by poire-z** [comment]
I can't trigger "grands" to be rendered hyphenated (so, some other code may decide to not use the hyphenation suggestion), but the debug output looks like it says it can:
```
word to hyphenate: ' grands '
  hyph pattern matched:  g 004 on  grands  000000000
  hyph pattern matched: gra 0100 on grands  04000000
  hyph pattern matched: gr 120 on grands  04000000
  hyph pattern matched: ra 100 on rands  4000000
  hyph pattern matched: ds 012 on ds  0000
Hyphenate: grand-|s  g4r0a0n0d1-|s2
```
In case that debug output can help you understand why.

**Comment by cramoisi** [comment]
Hyphenate: grand-|s  g4r0a0n0d1-|s2

Here is the problem : the rule `<pattern>d1s2</pattern>` (for inside a word) shows the cut, but the rule `<pattern>2s </pattern>` should have prevent it as it says "2" when s it at the end of the word...

**Comment by cramoisi** [comment]
So it seems crengine doesn't want to deal with some rules for some reasons (the problem is not in the pattern file here).

**Comment by poire-z** [comment]
Possibly a bug.
Your one letter patterns were parsed, but not checked (so never matched).
With just:
```diff
@@ -846,7 +846,7 @@ bool TexHyph::hyphenate( const lChar16 * str, int len, lUInt16 * widths, lUInt8
     memset( mask, '0', wlen+3 );
     mask[wlen+3] = 0;
     bool found = false;
-    for ( int i=0; i<wlen; i++ ) {
+    for ( int i=0; i<=wlen; i++ ) {
         found = match( word + i, mask + i ) || found;
     }
     if ( !found )
```
so possibly checking up to a string that starts at the last char, instead of up to a string that starts with the second last char, you get:
```
word to hyphenate: ' grands '
  hyph pattern matched:  g 004 on  grands  000000000
  hyph pattern matched: gra 0100 on grands  04000000
  hyph pattern matched: gr 120 on grands  04000000
  hyph pattern matched: ra 100 on rands  4000000
  hyph pattern matched: ds 012 on ds  0000
  hyph pattern matched: s  600 on s  120
  hyph pattern matched: s  600 on s  620
  hyph pattern matched: s  600 on s  620
Hyphenate: grand|s  g4r0a0n0d6|s2
```

Not sure why the `s` is checked/matched 3 times (with different mask) thus...
That was just a lucky try, I'll have to look more closely at the code if that's really what it's supposed to be, but I guess that's it.

**Comment by cramoisi** [comment]
> Not sure why the s is checked/matched 3 times (with different mask) thus...

The resulting pattern is correct  `Hyphenate: grand|s  g4r0a0n0d6|s2`... any idea on the 3 hits on the `s` ?

**Comment by poire-z** [comment]
> any idea on the 3 hits on the s

Yes. Internally, it makes 4 hashes for each pattern, for easier lookup. One from the 4 first letters of a pattern, another one from the 3 first letters, ...one from the 2 and one from the first letter.
Then, when looking for pattern for a word " grands ", it makes the same 4 hashes from the first letters from that word (so, " gra", " gr", " g" and " ").
Then it looks (quick thanks to the hashes) if there are patterns with the same of each of these 4 hashes.
If yes, for each, it goes look (slower) if further than these 1,2,3 or 4 first letters, the rest of the pattern matches the rest of the word. If yes, it applies the pattern flags to the word mask.
So, the 4,3 and 2 hashes for our single "s " pattern end up being the same, because it's only 2 letters. So, our multiple matches.

For your " grands " word, it goes like that:
```
word to hyphenate: ' grands '
checking word at 0
  checking hash4
  checking hash3
  checking hash2
     found hash2 ( g): 1
          hyph pattern matched:  g 004 on  grands  004000000
  checking hash1
checking word at 1
  checking hash4
     found hash4 (grandiloquent ): 0  <= the rest of the word does not match
  checking hash3
     found hash3 (gra): 1
          hyph pattern matched: gra 0100 on grands  04000000
  checking hash2
     found hash2 (phres ): 1
          hyph pattern matched: gr 120 on grands  14000000
  checking hash1
checking word at 2
  checking hash4
  checking hash3
  checking hash2
     found hash2 (ra): 1
          hyph pattern matched: ra 100 on rands  4000000
  checking hash1
checking word at 3
  checking hash4
  checking hash3
  checking hash2
  checking hash1
checking word at 4
  checking hash4
  checking hash3
  checking hash2
  checking hash1
checking word at 5
  checking hash4
  checking hash3
  checking hash2
     found hash2 (ds): 1
          hyph pattern matched: ds 012 on ds  0120
  checking hash1
checking word at 6
  checking hash4
     found hash4 (s ): 1
          hyph pattern matched: s  600 on s  620
  checking hash3
     found hash3 (s ): 1
          hyph pattern matched: s  600 on s  620
  checking hash2
     found hash2 (s ): 1
          hyph pattern matched: s  600 on s  620
  checking hash1
Hyphenate: grand|s  g4r0a0n0d6|s2
```

Well, I guess the above hyphman.cpp one char patch is ok :) 
Can you just add it in that PR, and revert your revert?
(Do you want a libcrengine.so with that small patch in so you can test it?)

**Comment by cramoisi** [comment]
> (Do you want a libcrengine.so with that small patch in so you can test it?)

yes !

**Comment by poire-z** [comment]
Here it is, built for Kobo: [libcre_hyphman_fix.zip](https://github.com/koreader/crengine/files/3206079/libcre_hyphman_fix.zip)

**Comment by poire-z** [comment]
(^ as we didn't bump any format version, you may need to toggle some rendering change (like font hinting, kerning, word spacing, font size, or margin... - and back) to see the new stuff or remove glitches)

**Comment by cramoisi** [comment]
ok !

**Comment by poire-z** [comment]
No more `6o `?

**Comment by cramoisi** [comment]
`6o` was me being paranoid :)

**Comment by poire-z** [comment]
Tell me when you think it's all fine to be merged.

And can you please do in this PR what I just forgot to do in #291 :( and increment this version number to `3.05.25k`:
https://github.com/koreader/crengine/blob/d81a8e2f34099f8d697d2c00212f88f001dea938/crengine/src/lvtinydom.cpp#L65

Just to force a re-rendering so users don't get the fixed hyphenation and kerning used when drawing, in boxes sized (and cached) with the unfixed code.

**Comment by poire-z** [comment]
^ sorry, that's not the one that needs to be changed.
We should just need to increment this less costly one, to `0x0019`
https://github.com/koreader/crengine/blob/d81a8e2f34099f8d697d2c00212f88f001dea938/crengine/src/lvtinydom.cpp#L66-L67

**Comment by cramoisi** [comment]
@poire-z So, I didn't change the CACHE_FILE_FORMAT_VERSION and I changed the FORMATTIONG _VERSION_ID ; it's ok ?

I've just read for two hours and half without problem, so i think it's ok to merge.

**Comment by poire-z** [comment]
Yep, all fine, thanks.

**Comment by cramoisi** [comment]
damn, I just got a `-q` ; `cin-q` :/

**Comment by poire-z** [comment]
Explainable?
Not just a matter of adding `>6q <` ?

**Comment by cramoisi** [comment]
Yes. This rule will be enough

**Pull request merged**
