### PR TITLE
Implement optional 8bpp dithering & image smooth scaling

### PR DESCRIPTION
**Pull request by NiLuJe**
As discussed in https://github.com/koreader/koreader/issues/1833 ;).

I expect the C++11 minor features (constexpr, nullptr) to fantastically blow up on the PB toolchain, so, this'll probably take a second PR with ifdeffery tweaks ;).

### CODE REVIEW

**Comment by poire-z** [comment]
I'll be using lvimg.cpp's LVStretchImgSource to resize background images (to solve https://github.com/koreader/koreader/issues/6345#issuecomment-653677740).
https://github.com/koreader/crengine/blob/487d8c293b58e472501bceca44cb623834e7f461/crengine/src/lvimg.cpp#L1955
https://github.com/koreader/crengine/blob/487d8c293b58e472501bceca44cb623834e7f461/crengine/src/lvimg.cpp#L2106
in lvrend.cpp's DrawBackgroundImage(), a bit like that:

```c
LVImageSourceRef img = enode->getParentNode()->getDocument()->getObjectImageSource(filepath);
int img_w =img->GetWidth();
int img_h =img->GetHeight();
[... some checks for CSS style width and  height ...]
if ( new_w != img_w || new_h != img_h ) {
     printf("bg image resized to w x h : %d %d\n", new_w, new_h);
     img = LVCreateStretchFilledTransform(img, new_w, new_h, IMG_TRANSFORM_STRETCH, IMG_TRANSFORM_STRETCH, 0, 0);
     img_w = new_w;
     img_h = new_h;
}
```
We would need it to stay a `LVImageSource/Ref` as it's then again passed to `LVCreateStretchFilledTransform()` for tiling and position shifting - and it would be best to not pass by a `LvDrawBuf` and back to a LVImageSource as this might affect colors and transparency (or we'd get back the mess I'll have removed with https://github.com/koreader/koreader/issues/6345#issuecomment-653763488).

You implemented in this PR smooth scaling (and dithering) when drawing a LVImageSource to a `LvDrawBuf`.
In case you're bored this summer, could you have a look at `LVStretchImgSource` and see if it would be feasible to have smooth scaling (and dithering if that makes sense) there too ?

My first test gave the following unsmooth scaling :)
<kbd>image</kbd>

**Comment by NiLuJe** [comment]
@poire-z: Are the h/v transform fields a bitmask, or can there only be a *single* one set?

**Comment by poire-z** [comment]
Nope, not a bitmask. Just one of:
https://github.com/koreader/crengine/blob/487d8c293b58e472501bceca44cb623834e7f461/crengine/include/lvimg.h#L92-L98
but transform_h might be one and transform_v an other.

(But it could be another function/class/method, like a new ResizeImage(). CoolReader only uses STRETCH for its own page background drawing.)

**Comment by NiLuJe** [comment]
@poire-z: Cool, might be doable then, just have to figure out which, if any, OnEndDecode is triggered ^^.

(I suck at OOP ;p).

**Pull request merged**
