### PR TITLE
Increase gamma values range

### PR DESCRIPTION
**Pull request by poire-z**
Taken from sergeyvl (pbchess) recent coolreader modifications to upstream:
https://gitlab.com/koreader/crengine-sergeyvl-mirror/commit/e27584d7d889088caab4b9dd683d90965dba3601
https://gitlab.com/koreader/crengine-sergeyvl-mirror/commit/4a2df8677a8d67d0e48fead278204b3e97d2cc55
https://gitlab.com/koreader/crengine-sergeyvl-mirror/commit/cc6c7bccd8b88306afa137cf34e75c7fc1e464f8

(with just a slight correction to generated comments: `15 `is still the _no modification_ value, and not `GAMMA_LEVELS/2`).

Increase gamma values range from originally:
`  gamma values: 0.3 ->  1.9 - indexes: 0 -> 30`
to:
`  gamma values: 0.3 -> 15.0 - indexes: 0 -> 56`
The first 0-30 indexes still map to the original gamma values, and index 15 is still gamma value 1.0 (no gamma change).

No change needed to base or frontend, and no impact to current gamma values.
In `defaults.lua`, we have:
```
-- crereader font gamma
DCREREADER_CONFIG_LIGHTER_FONT_GAMMA = 10
DCREREADER_CONFIG_DEFAULT_FONT_GAMMA = 15
DCREREADER_CONFIG_DARKER_FONT_GAMMA = 25
```
which are index values.
So one can change them to up to 56 to try darker gamma.
(Darker gamma are a bit ugly on the emulator, I'm curious about how they will look on our devices).

### CODE REVIEW

**Comment by Frenzie** [comment]
Oh, I was going to cherry-pick those. :-)

**Comment by poire-z** [comment]
If you prefer to cherry pick these (dunno how that works) so they appear as authored by sergeyvl (dunno if that works for remote authors), feel free to do it instead - I'll close this PR with no problem :)

**Comment by Frenzie** [comment]
You git cherry-pick by putting them in the same git repo. Something like

```bash
git checkout -b sergey
git reset HEAD~200 # common past
git pull https://sergey
# and now…
git checkout master
git checkout -b sergey-cherries
git cherry-pick hash
```

**Comment by poire-z** [comment]
Thanks for the easy procedure :) Hope I applied it well.

**Comment by Frenzie** [comment]
Yup, looks good. I like the preserved history. :-)

**Pull request merged**
