### PR TITLE
Avoid wrap on a space before or after some specific chars

### LINKED ISSUE #235: avoid new line before : ? ;  (and so on) in french
@poire-z : I don't know if you get this but in french, as there is a space before some punctuation and because the nbsp space doesn't work right, it's not uncommon to have a new line before them. (I usually replace them with fine space within calibre before reading to avoid this).

```
([«])(\u00a0|&#160;)|(&#160;|\u00a0)([;:!?»])
\1\u202F\4
```

### PR DESCRIPTION
**Pull request by poire-z**
Avoid a '(' at end of line, or a ')' at start of line, or a '?' at start of line with french texts (where some punctuation requires a space before). Closes #235.
It's the work of the publisher to use a no-break-space in these cases, but let crengine do a bit of this work he has not done. It mostly happens to me with random french web blog or news article (people don't bother with `&nbsp;` on the french web...) saved as EPUB.
Note that Firefox does not do anything special and let a `»` or a `?` at start of wrapped line.

I re-used chars from https://github.com/koreader/koreader/blob/c8d19b310c24888bf0c2e24a6865b8477fc1969f/frontend/util.lua#L231-L237, and I may have added a few others while looking at the list of chars in the crengine file.

I guess there's no question for some chars like `(|{;:?!`.
Not sure about the other like arithmetic `+*-%` and the `$` sign, so comments welcome if you can think of contexts/languages where we should not enforce such a no wrap.

(Just thought in english, one writes `$100`, in french `100$`, dunno if it happens people add a space `$ 100`  or `100 $`, but I added avoid wrap on both sides of it, so we won't see
```
[...] and he looked and found $
100 in his purse and went [...]
```

### CODE REVIEW

**Comment by poire-z** [comment]
Unrelated last commit just to add a yet-unused helper function, to solve https://github.com/koreader/koreader/issues/4134#issuecomment-428617973.

**Comment by Frenzie** [comment]
$ 100 or € 100 is very normal.

**Comment by cramoisi** [comment]
@poire-z thanks a lot ! It's working great ! It was the only thing left from my day 1 "list of thing koreader could do better" \o/

**Comment by poire-z** [comment]
Good :)
I would still like you to confirm (with the `View HTML` helper) that a few places where it bugged you in the past do not contain a no-break-space, contrary to what you thought :)

**Comment by cramoisi** [comment]
@poire-z : the first book, it's only classic blank spaces before punctuation ; it's ok now.
the second book, it was no-break space :-) and it's ok now.

**Pull request merged**
