### PR TITLE
Various sizing, body and color fixes

### PR DESCRIPTION
**Pull request by poire-z**
### Fix sizing of float/inline-block image containers

The floatBox or inlineBox container of an image could be larger than then drawn image (ie. when the image is itself larger than the screen size) as images are later resized to fit the screen. Account for that at rendering time, so we don't get empty space after the image in such containers.
This fixes the issue noticed by @NiLuJe (and me on some books :), analyzed at https://github.com/koreader/koreader/issues/8384#issuecomment-962491275 .
Before | After:
image

### Fix body background drawing and other clipping issues

Body background-color and background-images were handled differently:
- background-color applied wrongly to the border-box.
- background-image applied correctly to the whole canvas, but could paint over the left page in 2-pages mode and over the top status bar, and in-page footnotes' body background could paint over the whole content.

Handle them both similarly according to CSS specs, try to do the right thing in both scroll and page modes, whether in 1-page or 2-pages modes.
Avoid using `SetClipRect(NULL)` which was the reason for painting over other stuff: compute proper clips for body backgrounds and for content overflow (inline-block, drop caps), store them in an adhoc field in DrawBuf to make them more easily reachable.
For content overflow, limit clip to below the top header, and to above any in-page footnotes, so these don't get drawn over.

This fixes the issue noticed at https://github.com/koreader/crengine/pull/327#issuecomment-1025216808 , and we now get:
image
image

Other comparisons, Before | After:

image

image

### Drawing: don't use setHidePartialGlyphs()

It's not clear what it aims to solve, and its behaviour is odd and feels buggy.

### CSS: ignore the `<body>` parent of `<DocFragment>`

The container of EPUB's `<DocFragment>` is unfortunately made a `<body>` element: it shouldn't match any selector in any stylesheet.
See https://github.com/koreader/koreader/issues/8791#issuecomment-1032999067 for details.
Should allow closing https://github.com/koreader/koreader/issues/8791.

### CSS colors: parse rgb()/rgba() and 4/8 digits hex values

Parse/handle correctly the presence of the alpha component, but this alpha component is ignored for now as support for drawing alpha needs more work.
Should allow closing https://github.com/koreader/koreader/issues/8814.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/467)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Very fancy!

**Comment by poire-z** [comment]
About the last commit: it doesn't handle (yet?) the alpha/opacity/transparency component.
Would we want that ?

I got this working with some small tweaks to LVDrawBuf (that will need @NiLuJe to have a good review and optimisation pass):
FillRect:
image
Draw glyph bitmap:
image

It will need me to have a look at the whole text/color drawing, because there are some kind of keywords (https://github.com/koreader/crengine/pull/419#discussion_r573097717) for color values, that gets in the way of really using the 4 bytes for colors - and may be some rework of the whole color inheritance (haven't really investigated).

**Comment by NiLuJe** [comment]
IIRC, CRe has an actual RGBA data type that you'll want to use, because you probably definitely do *not* want to do alpha-blending at the CSS parsing stage ;).

**Comment by poire-z** [comment]
> you probably definitely do _not_ want to do alpha-blending at the CSS parsing stage ;).

And what would/could I want to alpha-blend at the CSS parsing stage ? :)

> IIRC, CRe has an actual RGBA data type that you'll want to use, because

Well, it's the single color type: 4 bytes, the upper one being currently 0 meaning full opacity.
And we would deal with it only when it's appropriate, at drawing time :)

ie. for the gray buffer:
```diff
@@ -905,6 +905,7 @@ void LVGrayDrawBuf::FillRect( int x0, int y0, int x1, int y1, lUInt32 color32 )
     if (x0>=x1 || y0>=y1)
         return;
     lUInt8 color = rgbToGrayMask( color32, _bpp );
+    const lUInt8 opacity = 0xFF - (color32>>24);
 #if (GRAY_INVERSE==1)
     color ^= 0xFF;
 #endif
@@ -926,8 +927,15 @@ void LVGrayDrawBuf::FillRect( int x0, int y0, int x1, int y1, lUInt32 color32 )
                 line[index] = (lUInt8)((line[index] & ~mask) | (color & mask));
             }
         } else { // 3, 4, 8
-            for (int x=x0; x<x1; x++)
-                line[x] = color;
+            if ( opacity == 0xFF ) {
+                for (int x=x0; x<x1; x++)
+                    line[x] = color;
+            }
+            else {
+                const lUInt8 alpha = 0xFF-opacity;
+                for (int x=x0; x<x1; x++)
+                    ApplyAlphaGray8( line[x], color, alpha, opacity );
+            }
         }
         line += _rowsize;
     }
@@ -1252,6 +1260,7 @@ void LVGrayDrawBuf::Draw( int x, int y, const lUInt8 * bitmap, int width, int he
     if ( _bpp==8 ) {
         lUInt8 * dstline = _data + _rowsize*y + x;
         const lUInt8 color = rgbToGrayMask(GetTextColor(), 8);
+        const lUInt8 bmpopacity = 0xFF - (GetTextColor()>>24); // will need better renaming
         while (height--)
         {
             const lUInt8 * __restrict src = bitmap;
@@ -1259,6 +1268,7 @@ void LVGrayDrawBuf::Draw( int x, int y, const lUInt8 * bitmap, int width, int he
             size_t px_count = width;
             while (px_count--)
             {
+                /*
                 const lUInt8 opaque = (*src++);
                 if ( opaque == 0 ) {
                     // Background pixel, NOP
@@ -1268,6 +1278,19 @@ void LVGrayDrawBuf::Draw( int x, int y, const lUInt8 * bitmap, int width, int he
                     const lUInt8 alpha = opaque ^ 0xFF;
                     ApplyAlphaGray8( *dst, color, alpha, opaque );
                 }
+                */
+                lUInt8 opacity = *(src++); // glyph opacity
+                if ( opacity == 0 ) {
+                    // Background pixel, NOP
+                }
+                else if (opacity == 0xFF && bmpopacity == 0xFF) { // opaque color
+                    *dst = color;
+                }
+                else {
+                    opacity = (opacity*bmpopacity)>>8;
+                    const lUInt8 alpha = 0xFF-opacity;
+                    ApplyAlphaGray8( *dst, color, alpha, opacity );
+                }
                 dst++;
             }
             /* next line, accounting for clipping in src and padding in dst */
```

**Comment by NiLuJe** [comment]
I was waylaid by the commented out stuff ;o).

I'll need a working brain for this, so, probably next WE ;).

**Comment by poire-z** [comment]
@NiLuJe : how would you prefer to have this updated? : 

https://github.com/koreader/crengine/blob/b0fdab357637e9b3aa407e5dfa102adc3c303f68/crengine/src/lvdrawbuf.cpp#L1938-L1969

Just this code adapted where needed:
```c
    } else {
        const lUInt32 bmpcl32 = bmpcl & 0x00FFFFFF;
        const lUInt8 bopacity = ~bmpcl >> 24; // alpha=0x00 => opacity=0xFF
        if (bopacity == 0) // Fully transparent color
            return;

        while (height--)
        {
            const lUInt8 * __restrict src = bitmap;
            lUInt32 * __restrict dst = ((lUInt32*)GetScanLine(y++)) + x;

            size_t px_count = width;
            while (px_count--)
            {
                // Note: former code was considering pixel opacity >= 0xF0 as fully opaque (0xFF),
                // not sure why (it would save on the blending computation by 5% to 15%).
                lUInt8 opacity = *(src++); // glyph pixel opacity
                if ( opacity == 0 ) {
                    // Background pixel, NOP
                }
                else if (opacity == 0xFF && bopacity == 0xFF) { // fully opaque pixel and color
                    *dst = bmpcl32;
                }
                else {
                    opacity = (opacity*bopacity)>>8;
                    const lUInt8 alpha = 0xFF-opacity;
                    const lUInt32 cl1 = ((alpha*((*dst)&0xFF00FF) + opacity*(bmpcl32&0xFF00FF))>>8) & 0xFF00FF;
                    const lUInt32 cl2 = ((alpha*((*dst)&0x00FF00) + opacity*(bmpcl32&0x00FF00))>>8) & 0x00FF00;
                    *dst = cl1 | cl2;
                }

                dst++;
            }
            /* next src line, accounting for clipping */
            bitmap += bmp_width;
        }
    }
```

Or going smaller and reusing your ApplyAlphaRGB:
```c
    } else {
        const lUInt32 bmpcl32 = bmpcl & 0x00FFFFFF;
        const lUInt8 alpha = (bmpcl >> 24) & 0xFF;
        if (alpha == 0xFF) // Fully transparent color
            return;

        while (height--)
        {
            const lUInt8 * __restrict src = bitmap;
            lUInt32 * __restrict dst = ((lUInt32*)GetScanLine(y++)) + x;

            size_t px_count = width;
            while (px_count--)
            {
                // Note: former code was considering pixel opacity >= 0xF0 as fully opaque (0xFF),
                // not sure why (it would save on the blending computation by 5% to 15%).
                lUInt8 opacity = *(src++); // glyph pixel opacity
                if ( opacity == 0 ) {
                    // Background pixel, NOP
                }
                else {
                    lUInt8 palpha = opacity == 0xFF ? alpha : 0xFF - ( ((alpha^0xFF) * opacity)>>8 );
                    ApplyAlphaRGB(*dst, bmpcl32, palpha);
                }

                dst++;
            }
            /* next src line, accounting for clipping */
            bitmap += bmp_width;
        }
    }
```
with the expense of having your ApplyAlphaRGB() doing some redundant `^` and `&=` ?
(Smaller, but it took me one hour to get  `0xFF - ( ((alpha^0xFF) * opacity)>>8 )` right... Using `~` instead of `0xFF` stuff as with `~(~alpha...)` was a bad idea when the intermediate values are larger than a lUInt8 I guess :) I hate these bitwise arithmetics...)
I guess reusing your ApplyAlphaRGB() will make it easier to adapt the other bpp code paths.

But, hum, do we want that? Clearer and more academically correct lvdrawbuf code, but a little bit more computations.
And it feels supporting alpha colors could only degrade legibility vs. not supporting them (ensuring everything text is opaque and easier to read :)

**Comment by NiLuJe** [comment]
I kinda like the first option, as the fiddling around to mix pixel, background & fill color muddies things up in the second one ;).

I'd basically only change the the `0xFF - $var` stuff to `$var ^ 0xFF` for consistency with the rest of the code ;).
(And the spacing, bracing and ordering of the actual blending computation to match the one in ApplyAlpha* ;)).

**Comment by NiLuJe** [comment]
I don't really have any bright ideas, but I vastly prefer the old behavior ;o).

**Comment by poire-z** [comment]
I got one.
This should probably not be dealt with when we draw a glyph (and passing baseline/line height and computing stuff there for each glyph would be a bit ugly).
It's probably better in lvtextfm when processing each line of a paragraph: currently, we process each line that is partially or fully in the clip, which is right. And what we check here is the line box in question, which might be smaller than the glyphs it contain.
Once we have accepted the line here, we can check again if it's full or partial:
- if it's full, tweak the clip so we don't truncate the glyphs that may extend beyond the line box. This should catch all main paragraph's lines that were splitted to make pages.
- if it's partial (so, float, inline boxes, tables, bigger stuff we couldn't split pages at boundaries), don't tweak the current clip (and have their glyphs truncated).

This is currently (the accent on the é in témoignent on the first line is truncated).
image

This is what we get if we set a NULL clip to the "full" lines:
image

(The fact that with clip=NULL, we get some bits of the first line top glyphs over the top status bar, means we need alternative clips, and a different one for the main content, and for the the footnotes, so still needs some thinking :) but it feels like the right way to handle this.

The line boxes (that glyphes can overflow) that we could be checking are actually what makes our highlights:
image

**Comment by NiLuJe** [comment]
Oh, I was going to post a shower thought, but it was apparently about another bit of the issue entirely, possibly an irrelevant one ;p.

So, here goes nothing:

I have no idea how the clip and line box are currently calculated, but I was thinking that it might be easier to just deduce the ascenders & descenders from lines that should overflow, instead of computing what goes above the previous baseline (and/or page/box top) and below the current baseline.

**Comment by poire-z** [comment]
cf https://www.mobileread.com/forums/showthread.php?t=352648

Looks like in the first commit of this PR, I forgot to account for our "interline scale factor" :/
This seems to fix the issue mentionned on the sample epub provided:
```diff
--- a/crengine/src/lvtinydom.cpp
+++ b/crengine/src/lvtinydom.cpp
@@ -20350,6 +20350,10 @@ int ldomNode::getSurroundingAddedHeight(bool account_height_below_strut_baseline
                     if (line_h < 0) { // shouldn't happen
                         line_h = n->getFont()->getHeight(); // line-height: normal
                     }
+                    int interline_scale_factor = getDocument()->getInterlineScaleFactor();
+                    if ( style->line_height.type != css_val_screen_px && interline_scale_factor != INTERLINE_SCALE_FACTOR_NO_SCALE ) {
+                        line_h = (line_h * interline_scale_factor) >> INTERLINE_SCALE_FACTOR_SHIFT;
+                    }
                     int f_half_leading = (line_h - fh) / 2;
                     int baseline_to_bottom = line_h - fb - f_half_leading;
                     // Account the height below the strut baseline (but not
```

**Pull request merged**
