### PR TITLE
lvdocview: remove (unused) `crskin` and `wolutil` related code

### PR DESCRIPTION
**Pull request by benoit-pierre**
Will allow https://github.com/koreader/koreader-base/pull/1675.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/542)

### CODE REVIEW

**Comment by poire-z** [comment]
I know there is a lot of stuff we don't use in crengine - but let's keep it so 1) we're not the ones breaking the link with other forks and their ability to pick our stuff and 2) it has happened that looking at that unused stuff gives some explanations of why some stuff/arguments/logic in remote stuff we do use is as it is - so it's best if all the context is kept.
So, better wrap if under `#if USE_THAT_THING` (or `#if 0` at worst).

**Comment by benoit-pierre** [comment]
With the amount of custom changes, I think it makes more sense to not be shy about simplifying stuff. Reduce the barrier to entry, reduce the complexity, reduce compilation time, reduce the final library size, reduce the amount of code you have to wade through…

If you want to keep stuff for archeological spelunking, make a branch before cleaning up (I would in fact go as far as removing those unused files too, again less to stuff to wade through).

**Comment by poire-z** [comment]
> Reduce the barrier to entry, reduce the complexity, reduce compilation time, reduce the final library size, reduce the amount of code you have to wade through…

You're not losing all that with `#if`'ing (and `#if 0` if you really have to, so they look like comments in vim). And I keep my context.
I don't care about the barrier to entry.
I've been doing archeological work for the last 7 years, and there's no doubt this will be needed again, so don't make a barrier to continue :)

**Comment by benoit-pierre** [comment]
Grep does not care about `#if 0`, but ok…

**Comment by poire-z** [comment]
> Grep does not care about `#if 0`

Which is perfectly welcome for my archeological use case.
(And even yours: if you want to change a thing, good to find out why it was made that way, and get confirmations with the possible workarounds in these places that there's indeed something tricky.)

> but ok…

Thanks!

**Comment by Frenzie** [comment]
> Grep does not care about #if 0

I believe that was the very point! :laughing:

**Review by poire-z — COMMENTED** [review]
I don't mind removing the other stuff, just keep the long LVDocView::exportWolFile() implementation wrapped in `#if 0`.
(I remember I once did find in there some explanation  for some stuff present elsewhere, may be some TOC or drawBuf stuff - so it will be good to still be able to find some methods possibly only used in there - and now unused. That you could `#if 0` if you really want to then :)

**Pull request merged**
