### PR TITLE
Add list-style-type: none

### PR DESCRIPTION
**Pull request by Frenzie**
References https://github.com/koreader/koreader/issues/2859

### CODE REVIEW

**Comment by Frenzie** [comment]
@poire-z These failures are going to get annoying. But that's kind of the point. :-P Any comments on this PR? It seems like it couldn't be any simpler (and it works, obviously), but a second opinion before merging never hurts.

**Comment by poire-z** [comment]
`marker = L"\x0020";` is a space, with some width then ? No unwanted indentation with that ? Shouldn't it be just `""` ?
(crengine is annoying enough by itself, it didn't need any help :)

**Comment by Frenzie** [comment]
No, it's good. Without that there's an unwanted *lack* of indentation.

## With `""`
screenshot_2018-03-06_22-08-11

## Comparison with square
screenshot_2018-03-06_22-08-21

## Browser (Firefox 58) for reference
screenshot_2018-03-06_22-09-20
screenshot_2018-03-06_22-09-33

**Comment by poire-z** [comment]
I was rather thinking about when a very long sentence is wrapped, before another list item came into play.
But I guess all such wrapped lines are aligned, and that the marker is outside the paragraph, just like with squares. So I guess it should be fine.

**Comment by Frenzie** [comment]
If there is a problem it exists with each and every list style. Just check a couple of lines above and below. ;-)

**Comment by poire-z** [comment]
(Just a quick note, so I can later link to this observation)

When `list-style-position: inside`,  `list-style-type: none` should take no space, as shown by Firefox:

<kbd>image</kbd>

I'll fix that in a later PR, as it should also be done with my rendering hacks of behaving like `inside` when `outside` and `text-align right` or `center`.

**Pull request merged**
