### PR TITLE
Updated German patterns

### PR DESCRIPTION
**Pull request by zwim**
These are the newly updated patterns.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/455)

### CODE REVIEW

**Comment by poire-z** [comment]
How come these patterns change so often - and so much ? Is German still a work-in-progress ? :)

**Comment by zwim** [comment]
As said some PRs earlier, the patterns are from http://projekte.dante.de/Trennmuster which is a project of the German TeX/LaTeX users group. I just create the patterns from their sources https://repo.or.cz/w/wortliste.git once a month (or every other month).
Then I do a PR, so that other KOReader users also do have the latest version.

If you think I update the patterns too often, please tell me an appropriate frequency. :)

And yes, this is a living project with quite some changes.

**Comment by poire-z** [comment]
I was not complaining/asking about your PR, and the frequency is fine.

Just asking/curious why this German TeX/LaTeX users group has to change them so often and so much. 
t might be a "living project", but the language is old and would only need small tweaks for new words or small corrections for words we meet rarely.
Or is there something specific with German ? Its long composite words maybe ? And everytime you change a thing for a new word, you need to update many other patterns to not get them to trigger the same way as before ?

**Comment by zwim** [comment]
In German we have a lot of long and composed words, as well as word loanwords (also from ancient languages like Latin and Greek). There are some general rules how to hyphenate. The Trennmuster-group has the claim to generate "good" hyphenation positions and to suppress ambiguous or misleading ones. 

An often used example would be: "Urinstinkt" (basic instinct) should not be hyphenated as "Urin-stinkt" (which would mean urine stinks).

>Or is there something specific with German ? Its long composite words maybe ? And everytime you change a thing for a new word, you need to update many other patterns to not get them to trigger the same way as before ?

Yes, this is also true!

**Pull request merged**
