### PR TITLE
Uplift German hyphenation patterns

### PR DESCRIPTION
**Pull request by zwim**
Well, I was lazy. The last update was 9 months ago. ;)
Maybe this PR will find its way into 2023.12?

Happy new year and a peaceful Christmas for all!!!

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/549)

### CODE REVIEW

**Comment by Frenzie** [comment]
```
cr3gui/data/hyph/German.pattern:36780: parser error : Comment not terminated 
<!--
See: http://projekte.dante.de/Trennmuster/WebHome

^
cr3gui/data/hyph/German.pattern:36780: parser error : Start tag expected, '<' not found

^
```

**Comment by poire-z** [comment]
Sorry, forgot about this PR. Given the initial christmas enthusiasm and broken XML, I thought it would better wait for the new year sobriety :)
Dunno if it's safe to bring it with the crengine fix bump for the coming up stable :/

**Comment by Frenzie** [comment]
The changes are very minor. Whatever would be better or worse are probably just some edge cases.

**Comment by poire-z** [comment]
So, merging & bumping ?

**Comment by Frenzie** [comment]
Let's do it. You can blame me if someone complains `Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz` is suddenly no longer correctly hyphenated. ;-D

**Pull request merged**
