### PR TITLE
Use transparent colors on battery-symbol

### PR DESCRIPTION
**Pull request by zwim**
Use transparency on the batter symbol -> nightmode.
This should solve https://github.com/koreader/koreader/issues/7750

Tested on emulator (with/without color rendering) and on a Tolino.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/447)

### CODE REVIEW

**Comment by poire-z** [comment]
I let @NiLuJe review this (as it is drawing stuff I never really had to care for, thanks to him :)

(Could there be a better name for the variable than `use_opaque` ? its meaning feels a bit opaque/unclear :) I guess it just disables the effect of the `invert` flag that gets in play at some point, from where? I haven't looked.)

**Comment by NiLuJe** [comment]
I'm not super fond of adding another boolean trap to the function signature just for that, and I also agree that the variable name doesn't make much sense to me ;).

That said, I don't really have any better idea (other than not caring about it ;p), and I don't really have time to think about it until the next couple of weeks ;).

**Comment by NiLuJe** [comment]
(I'd much rather directly invert the battery bitmap or something)

**Comment by zwim** [comment]
You are both right, the name was sh....

@NiLuJe Inverting the battery bitmap directly could be an option, but I am not sure if this would be more straight forward as a flag to undo the killing of transparency (introduced in https://github.com/koreader/crengine/pull/289)

I leave this PR open for now.

**Comment by poire-z** [comment]
As an alternative, see https://github.com/koreader/koreader/issues/7750#issuecomment-894961086.
We do that at the top of base/cre.cpp, could be a matter of calling it again with another parameter when toggling night mode.

**Comment by poire-z** [comment]
Closing this as inactive.
(I think a better solution might be to have frontend signal cre.cpp to transmit another set of icons when nighmode is toggled - with probably no change needed to crengine.)

**Pull request closed without merging**
