### PR TITLE
Various fixes: dot in paths, CSS transparent color, line-height

### PR DESCRIPTION
**Pull request by poire-z**
#### Supports './' and '/./' in file paths/href in EPUB

See https://github.com/koreader/koreader/issues/4353#issuecomment-479858881

#### Text rendering: ensure strut height on empty lines

Small thing missed in #273

#### CSS: adds support for color 'transparent' 

See https://github.com/koreader/crengine/issues/176#issuecomment-478321727

#### Fix getPageDocumentRange() on some pages (again)

More generic implementation of #105. See there for details. In some cases, this could happen at start too.

### CODE REVIEW

**Comment by Frenzie** [comment]
Btw, not necessarily too relevant for us, but on Win32 it's `\`, not `/`.

**Comment by poire-z** [comment]
Oh, right, I should use `separator` (which is `/` or `\` depending of stuff) instead of `cs16("/")`

**Comment by Eduardomb22** [comment]
Is this up already?

**Comment by poire-z** [comment]
Nope, not yet. I'll bump it today, so it will be in tomorrow's nightly.

**Pull request merged**
