### PR TITLE
prevent crash

### PR DESCRIPTION
**Pull request by frankyifei**
when len==63, it may crash as well

### CODE REVIEW

**Comment by houqp** [comment]
are you also going to submit this fix to upstream?

**Comment by houqp** [comment]
Good catch btw ;) This is the kind of issue that can totally be detected with static analysis.

**Comment by frankyifei** [comment]
It's not common that word length is so long. and I tried scan-build, it gave nothing.

**Comment by houqp** [comment]
Interesting... I would expect the out of bound check to be agnostic to array length. I also tried coverity before, which caught more bugs compared to llvm's analyzer.

**Pull request merged**
