### PR TITLE
better to keep MAX_WORD_SIZE=64

### PR DESCRIPTION
**Pull request by frankyifei**

### CODE REVIEW

**Comment by frankyifei** [comment]
I still don't know why the original code can work on pc but not on kindle. Is there any difference with the out of bounds check between the two platform?

**Comment by houqp** [comment]
Do we know which line it's crashing at?

**Comment by frankyifei** [comment]
line 686 and line687. when len==64, word[] has 64+3=67 elements. but these two lines write to word[67] and word[68]

**Comment by frankyifei** [comment]
oh, I did not consider when len==63, it will be similar to this bug when len==64

**Comment by houqp** [comment]
I see... The stack layout in x86 and ARM is very different. Since `words` is allocated on the stack, it very possible that in ARM, the overbound write corrupted the return address of the caller. While in x86 it only corrupts another stack variable.

**Pull request merged**
