### PR TITLE
Status line correct 00:15->12:15 AM

### PR DESCRIPTION
**Pull request by zwim**
This should fix https://github.com/koreader/koreader/issues/8790

grafik

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/465)

### CODE REVIEW

**Comment by poire-z** [comment]
Feels like déja vu :) https://github.com/koreader/crengine/pull/410#pullrequestreview-575573763


If you look at my multiple "forced pushed" difs, you'll see I added these strftime, and removed them in the last one :/ I have no idea why - unless it's in the next comment/discussion where it's suggested strftime would not work on Win32. May be these could/should be wrapped in #ifdef , using the old code, even if bad, if Windows ? Just so to not break upstream CoolReader if they end up picking again our stuff ?
I let @NiLuJe have the final word on this :)

**Comment by NiLuJe** [comment]
I do remember the discussions about it, I don't quite remember what we settled on, though :D.

**Comment by NiLuJe** [comment]
Unless we do the same fancy stuff as in front, basic strftime is also standard.

**Comment by poire-z** [comment]
>  I don't quite remember what we settled on, though :D.

https://github.com/koreader/crengine/pull/410#discussion_r564074624
You suggested that it may break the build on Win32.
And me not wanting to be held responsible for that :)

But if we wrap this with some #ifdef (there must be other stuff Windows-specific already wrapped), we could get both good and not-breaking.

**Comment by Frenzie** [comment]
The elusive KOReader win32 (or win64) build is farther off than ever btw, since WSL2 can just run it graphically without any issues.

**Comment by poire-z** [comment]
Not (ever :)) thinking about KOReader Win32, but about upstream CoolReader Win32 - that we should try to not break (even if not now, when/if they pick our changes) even if it doesn't affect us directly.

**Comment by NiLuJe** [comment]
> > I don't quite remember what we settled on, though :D.
> 
> [#410 (comment)](https://github.com/koreader/crengine/pull/410#discussion_r564074624) You suggested that it may break the build on Win32. And me not wanting to be held responsible for that :)
> 
> But if we wrap this with some #ifdef (there must be other stuff Windows-specific already wrapped), we could get both good and not-breaking.

That comment was specifically about the fancy GNU/POSIX-only tokens. If we keep to ANSI C and/or C99, we're good.

If we happen to *like* the fancy behavior, then , yeah, by all means, ifdef it away ;).

**Comment by poire-z** [comment]
What about this PR ? :)
May be just keep the old stuff, and wrap each change with:
```c
#if defined(_WIN32)
    old stuff
#else
    your new stuff
#endif
```
We don't care if this catches all unsupported plateform, we'll just pretend we thought about it and did something :)

**Comment by zwim** [comment]
In that way?

**Comment by poire-z** [comment]
Yep.
Let's wait for @NiLuJe 's ok.

**Comment by NiLuJe** [comment]
Might not even need an ifdef given the tokens used? Can't check ms docs right now ;).

**Comment by poire-z** [comment]
There is this variation in other places:
`#ifdef _WIN32`
But I don't see any:
`#if _WIN32`

**Comment by NiLuJe** [comment]
Yeah, https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=msvc-140 says this is supported, no need for ifdefs ;).

We do fancier things in our Lua utils, hence the trickery there ;). This is way more standard (-ish).

**Comment by poire-z** [comment]
> https://github.com/koreader/crengine/pull/410#discussion_r564074624

You needed a year to check the docs ?! :)
Or the docs changed?
Or upstream people (the only ones doing Win32 build) may use older compilers ?
Let them remove this #ifdef if/when they pick this and feel the old behaviour is buggy too?
Or let them add some #ifdef if/when it does not build ?

**Comment by NiLuJe** [comment]
IIRC, the year ago version was attempting the same trickery we do in Lua, which would actually have been a no-no ;).

This one's fine ;).

**Comment by poire-z** [comment]
OK, so let's revert last commit. Sorry @zwim :/

**Comment by zwim** [comment]
No problem. Good things come to those who wait. ;)

**Pull request merged**
