### PR TITLE
[CI] Add .codacy.yml

### PR DESCRIPTION
**Pull request by Frenzie**
Mainly to ignore what would otherwise be a lot of useless noise.

### CODE REVIEW

**Comment by Frenzie** [comment]
However… it's basically just using cppcheck so maybe this PR has no added value and shouldn't be merged. Or perhaps it'd be useful as a backup? This here seems to be the only useful thing it's currently saying:

screenshot_2019-02-16_16-47-00

**Comment by poire-z** [comment]
I don't know what codacy is or does, so I trust you on this.
(I just hope it won't add too much to the validation durations of PRs)

**Comment by Frenzie** [comment]
For our purposes it's almost exactly the same as this line:

https://github.com/koreader/crengine/blob/fd290a9251d0de628794d716c4083098b838a546/.ci/script.sh#L34

The difference is that for better and worse, you don't have to know the details. Which is why I just enabled it on android-luajit-launcher instead of manually setting up [PMD](https://pmd.github.io/). I then had this idea that I could also enable it here, but when you get right down to it I already set up a more informative combination of programs with cppcheck *and* clang-tidy.

But the advantage of Codacy is that it remembers and easily shows all of the (two) issues, at least if you visit the website.

> (I just hope it won't add too much to the validation durations of PRs)

It's in parallel so it shouldn't really matter. I suppose I'll just put this configuration file in the repo and we'll try it out for a bit. If we don't like it, we can just disable it again.

**Comment by Frenzie** [comment]
Oh yeah, and we could put a badge in the README that says crengine has an **A** code quality rating. ;-D

**Pull request merged**
