### PR TITLE
[CI] script.sh: test if *.pattern is valid XML

### PR DESCRIPTION
**Pull request by Frenzie**

### CODE REVIEW

**Comment by cramoisi** [comment]
even though I think @poire-z has shown that crengine doesn't really care to deal with a valid xml or not :)

**Comment by Frenzie** [comment]
I care and I don't care what crengine thinks. -p

**Comment by cramoisi** [comment]
let's show it how to think right ;)

**Comment by poire-z** [comment]
> @poire-z has shown that crengine doesn't really care to deal with a valid xml

I was wrong when I said that :)
Looking again this morning after I saw you had some XML comments in your French.pattern, it uses some XMLParser and react onTag, onText.
I guess you tested that your commented patterns were not taken into accounts, so that confirms it's a XML Parser and that it ignores comments.

**Comment by cramoisi** [comment]
Yup, I tested that. I add the extreme rules inside the classical pattern 1. to not loose them 2. because I have an .sh which run after update to remove the commented lines and auto-enable theses rules. But I can remove them if anything goes wrong (I shouldn't happen though)

**Pull request merged**
