### PR TITLE
Fix: Breaking opening quotation marks

### PR DESCRIPTION
**Pull request by robert00s**
This patch should fix: https://github.com/koreader/koreader/issues/914
Breaking opening quotation marks and comma following em dash #914

### CODE REVIEW

**Comment by Frenzie** [comment]
Let's see, this whole shebang was introduced in 3ffe6944160ca1dcfffdbaf40d83da36d209be6b by @chrox 

I'm fine with removing the line in principle, but I don't really know what the effects on CJK would be.

**Comment by robert00s** [comment]
Unfortunately I do not know anything about CJK :(
Changes done by @chrox are too complicated to me

**Comment by Frenzie** [comment]
> Unfortunately I do not know anything about CJK :(

My problem exactly. :-P

I guess we need a simple test document in https://github.com/koreader/test-data that would show the effects but I don't even know what to test for.

Pinging @Hzj-jie who might know more.

**Comment by Hzj-jie** [comment]
Yes, I know Chinese. But I cannot really understand the original issue https://github.com/koreader/koreader/issues/914.
The place where this function is used (https://github.com/koreader/crengine/blob/d0854294e0a9259d9c160b5fe9c91a123a63528b/crengine/src/lvtextfm.cpp#L1183) also lacks comments. Looks like it tries not to break between several punctuation. Is this what the original issue said?

**Comment by poire-z** [comment]
I think I had read that part of the code (but made no modification to it) in the past, and even if the function is named `isCJKPunctuation`, I think the place where it is used deals with any kind of punctuation, CJK or general.
So, i'm not sure it is right to remove general punctiation from it :) Does text really display nicely with this modification ?

If I understand correctly the original issue, there is a wrong decision to where to wrap text for some kind of quotation marks, which happen to look to me like "left punctuation".
So, may be the right fix would be to add them to the set of what is considered `CJKLeftPunctuation` ?
@Hzj-jie : would these https://github.com/koreader/crengine/blob/master/crengine/src/lvtextfm.cpp#L996 chinese characters looks like/should behave like the left bottom quote on ` „quoted text” ` in the original issue ?

I think I have seen lately in some french texts some bad text wrap on some other quotation marks like
```
this was called «
something »
```
so it may need a fix for these too.
But when I saw them, I remembered something I fixed some months ago :
For well produced books, a no-break-space should have been put on one side of each of these quotes, and https://github.com/koreader/koreader/issues/2806 should take care of these.
May be the book of the original issue was well produced and had these no-break-spaces, and may display correctly now.
@robert00s : do you have some examples of texts that still do not display as they should?

**Comment by Hzj-jie** [comment]
Yes, I think in general, the characters in https://github.com/koreader/crengine/blob/master/crengine/src/lvtextfm.cpp#L996 should not be placed at the end of a line.

**Comment by poire-z** [comment]
Thanks. Actually, the first 2 chars on this line are some kind of non-CJK left quotation marks.
I think we could add to these a few additional left quotation marks, like `«` and `„`  (and some others?) , and the code would not wrap on them when they are stuck to the left of a word (with no space between them).
If there is a space between them and the word, it's another story :( (but the producer should have put a no-break-space there).

About the other problem with comma following em dash, well, I think it's even more complicated, depending if there's a space, a no-break-space, or nothing between them...
Or may be there are some of these "general punctuation" chars that should not be considered punctuation, and considered like a letter. That way, em-dash would be considered a standalone letter like `a`, and `-,` like `a,` would always stick together ?

I would also like `«` followed by a space and some chars to stick together, but that looks complicated.

**Comment by Frenzie** [comment]
> If there is a space between them and the word, it's another story :( (but the producer should have put a no-break-space there).

Or one of [these variants](https://en.wikipedia.org/wiki/Non-breaking_space#Width_variation) when nested. ;-)

**Comment by robert00s** [comment]
@poire-z Thanks for great work.
I also try add that code before:

```
    bool isCJKLeftPunctuation(lChar16 c) {
       return c==L'“' || c==L'‘' || c==L'「' || c==L'『' || c==L'《' || c==L'〈' || c==L'（' || c==L'【' || c==L'«' || c==L'„';
    }
```
and its work very well when floating punctuation is disabled.
Look at that screen:

screenshot 2017-08-17 16-58-37
screenshot 2017-08-17 16-59-26


There is a problem with floating punctuation enabled. Quotation marks, like `«` and `„` are outside text. It's better than before but not perfect. I have no idea how to fix it.


screenshot 2017-08-17 17-00-17
screenshot 2017-08-17 17-00-55

I tested on that file (own created txt file).
[example_tekst.txt](https://github.com/koreader/crengine/files/1231708/example_tekst.txt)

**Comment by poire-z** [comment]
I see.
I just tested that: if you remove/comment these 5 lines https://github.com/koreader/crengine/blob/master/crengine/src/lvtextfm.cpp#L1081-L1085, the floating on the left for these LeftPunctuation characters does not happen.
But I guess it was made on purpose, see the various commits around and after March 6th 2014 at https://github.com/koreader/crengine/commits/master/crengine/src/lvtextfm.cpp .

I don't like and use floating punctuation, so I don't know how things should naturally look, and if there should be floating punctuation on the left, but @chrox did work to make it happen :)

(It looks strange that one would use floating punctuation without text justfication like on your screenshot - but it seems there's no way to force text justification, other than with stylesheets ?!)

**Comment by robert00s** [comment]
I still think that this line should be removed :)

` (c >= UNICODE_GENERAL_PUNCTUATION_BEGIN && c <= UNICODE_GENERAL_PUNCTUATION_END) || `


When I add `c ==L'\"'` to `bool isCJKPunctuation(lChar16 c)`

```
    bool isCJKPunctuation(lChar16 c) {
       return (c >= UNICODE_CJK_PUNCTUATION_BEGIN && c <= UNICODE_CJK_PUNCTUATION_END) || \
       (c >= UNICODE_GENERAL_PUNCTUATION_BEGIN && c <= UNICODE_GENERAL_PUNCTUATION_END) || \
       (c >= UNICODE_CJK_PUNCTUATION_HALF_AND_FULL_WIDTH_BEGIN && c <= UNICODE_CJK_PUNCTUATION_HALF_AND_FULL_WIDTH_END) || \
        c == L'·' || c ==L'\"';
    }
```

screenshot 2017-08-17 17-59-31


and then `"` are no wrap

so what is difference between 'normal' quotation marks `"` and   `«` or `„`? :)

**Comment by Frenzie** [comment]
> so what is difference between 'normal' quotation marks " and « or „? :)

* `"` are typewriter "can't do proper typography" quotation marks
* `“”` are "normal" quotation marks (in English)
* «» are "normal" quotation marks (in French; in German it's the same but `»«`)

behavior-wise, probably nothing :-P

**Comment by poire-z** [comment]
Well, may be we could do that. It's just that this code is so complex that it's hard to guess side effects :)

From what I get, the code that uses isCJKPunctuation is trying to keep as much punctuation on the current line when splitting paraphaphs into lines.

But the overall split/wrap is done according to char properties defined elsewhere. It's quite well defined and distinguished for the firsts unicode ranges:
https://github.com/koreader/crengine/blob/master/crengine/src/lvstring.cpp#L3279-L4152 and https://github.com/koreader/crengine/blob/master/crengine/src/lvstring.cpp#L4154-L4170 (somehow, I thought that it would be there that we would need to remove GENERAL_PUNCTUATION to see some effect :)
(I also did my homework on them for word selection at https://github.com/koreader/crengine/blob/master/crengine/src/lvtinydom.cpp#L6573-L6604).

The problem is that the "general punctuation range" http://jrgraphix.net/r/Unicode/2000-206F https://en.wikipedia.org/wiki/General_Punctuation includes uncommon things i would consider punctuation, but also things i would consider part of a word (the quotations marks we are dealing with).
So, these would also need to be distinquished.

> so what is difference between 'normal' quotation marks " and « or „? :)

'Normal' quotation marks are considered "sign" or "nothing" in the lines highlighted above, they are not considered punctuation. Unlike the whole "general punctuation" range.

Well, I'm again lost in the various places that deals with chars for wraping and co...

May be we could try your suggestion, and see how it goes with our casual reading, and revert it or think again when we encounter strange things.

**Comment by robert00s** [comment]
Maybe somethink like that :
not remove all line but add `&& c!=0x201e` 

```
   bool isCJKPunctuation(lChar16 c) {
       return (c >= UNICODE_CJK_PUNCTUATION_BEGIN && c <= UNICODE_CJK_PUNCTUATION_END) || \
       (c >= UNICODE_GENERAL_PUNCTUATION_BEGIN && c <= UNICODE_GENERAL_PUNCTUATION_END && c!=0x201e ) || \
       (c >= UNICODE_CJK_PUNCTUATION_HALF_AND_FULL_WIDTH_BEGIN && c <= UNICODE_CJK_PUNCTUATION_HALF_AND_FULL_WIDTH_END) || \
        c == L'·';
    }
```

**Comment by poire-z** [comment]
Yes, that's the less risky solution :)

I tried to add your 0x201e into https://github.com/koreader/crengine/blob/master/crengine/src/lvstring.cpp#L4154-L4170 : there were already something specific for a subsection `ch>=0x2012 && ch<=0x2015` so I thought it would be the right place, but it had no effect :|

So, I guess that your place is the right place for that.
You may also add alongside your 201e the other chars on http://jrgraphix.net/r/Unicode/2000-206F that look like some "left quotation mark" to me (official doc and names on http://www.unicode.org/charts/PDF/U2000.pdf, they mostly advise them as "left" or "used for opening...")  :
2018 201A 201B 201C 201E 201F
and may be:
2035 2036 2037 ? (reversed prime)
2039  SINGLE LEFT-POINTING ANGLE QUOTATION MARK = left pointing single guillemet • usually opening, sometimes closing
2045? LEFT SQUARE BRACKET WITH QUILL
204C? BLACK LEFTWARDS BULLET

**Comment by poire-z** [comment]
Looks and works fine for me. Nothing strange on quick pages turning on a few books.

**Comment by poire-z** [comment]
It now needs crengine bump in koreader-base, then koreader-base bump in koreader, for it to be in next nightlys.
(It's always a bit laborious for me to do it with git command line, git submodule init, update... Is it possible to do that via github web ?)

**Comment by Frenzie** [comment]
Usually you just want to `git pull origin master` rather than figuring out the hash and such. Makes it a touch less laborious. You can also do something like `git pull --recurse-submodules`, though that might do more than you bargained for.

But yeah, not to my knowledge.

**Pull request merged**
